<%@ Page Language="C#" MasterPageFile="~/Tracking/TrackingModule.Master" AutoEventWireup="true" CodeBehind="InventoryConfig.aspx.cs" Inherits="ezMESWeb.Tracking.Inventory.InventoryConfig" Title="Inventory Tracking -- ezOOM" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>
<%@ Register Assembly="IdeaSparx.CoolControls.Web" Namespace="IdeaSparx.CoolControls.Web" TagPrefix="asp" %>


<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
 <script type="text/javascript" language="javascript">
   function showDropDown(source, ctr1name, ctr2name, ctr3name)
  {
  
    var sourceID = source.name;
    sourceID = sourceID.replace(/\$/g, '_');
    sourceID = sourceID.substring (0,sourceID.length-14);
    
    var product = sourceID+'drp' + ctr1name;
    var material = sourceID+'drp' + ctr2name;
    
    //var supplier = sourceID+'drp'+ ctr3name;


    var dropdown1;
    var dropdown2;



        
        if (source.options[source.selectedIndex].value == 'product')
        {
            dropdown1=document.getElementById(product);
            dropdown2=document.getElementById(material);
            //document.getElementById(supplier).style.display = 'none'; 
            
        }
        else
        {
            dropdown2=document.getElementById(product);
            dropdown1=document.getElementById(material);   
            //document.getElementById(supplier).style.display = 'block';

        }
        if (dropdown1.style.display == 'none')
        {
           dropdown1.style.display = 'block';
           dropdown2.style.display ='none';
        }    
         
  }
 </script>
<asp:ToolkitScriptManager ID="ToolkitScriptManager1" runat="server" />

<asp:Button ID="btnInsert" runat="server" Text="Insert" Width="147px" OnClick="btn_Click"/> 
<!-- table style="width: 100%; height: 423px; margin-right: 0px; margin-top: 0px; border : 2px solid #6FBD06; ">
      <tr>
         <td style="height: 117px; width: 353px;" -->
 <asp:panel id="pnlScroll" runat="server" width="100%" scrollbars="Horizontal">  
   <asp:UpdatePanel ID="gvTablePanel" runat="server" UpdateMode="Conditional">
            <ContentTemplate>
            <table width="80%">
                <tr style="height:30px;">
			        <td colspan ="3" align="center">
				        <asp:label id="title" runat="server"><b>Inventories</b></asp:label>
                    </td>
                </tr>
                <tr align="center">
                    <td align ="left" style="width:25%;">Part Name: <asp:TextBox id ="partName" runat ="server"></asp:TextBox></td>
                    <td align="left" style="width:35%;">Choose A Supplier: <asp:DropDownList id="drpSupplier" runat="server" Width ="170px" class="drpStyle" AutoPostBack="True" onselectedindexchanged="drpSupplier_SelectedIndexChanged"/></td>
                    <td align="left">Location: <asp:DropDownList id="drpLocation" Width ="170px" runat="server" class="drpStyle" AutoPostBack="True" onselectedindexchanged="drpLocation_SelectedIndexChanged"/><asp:Button id="Search" runat="server" Width ="100px" Text="Search" onclick="btnSearch_Click"/></td>
                </tr>
            </table> 
             <asp:label id="Message" forecolor="#FF3300" runat="server"/>
             <asp:CoolGridView ID="gvTable" runat="server" Caption="" 
                CssClass="GridStyle" GridLines="None" DataSourceID="sdsInventoryGrid" 
               EmptyDataText="No inventory currently available" 
               AutoGenerateColumns="False" AutoGenerateDeleteButton="True" DataKeyNames="id" FixHeaders="true" OnRowCommand="GridView_RowCommand"
               onselectedindexchanged="gvTable_SelectedIndexChanged" AllowPaging="True"  AllowSorting="true" PageSize="15" Width="1024px" Height="480px" AllowResizeColumn="true" 
               PagerStyle-BackColor="#f2e8da" PagerSettings-Mode="NumericFirstLast" 
           
               EnableTheming="False" onpageindexchanged="gvTable_PageIndexChanged">
                 <Columns>
                     <asp:TemplateField>
                         <ItemTemplate>
			               <asp:LinkButton ID="relocate" runat="server" CommandName="EditLocation" Text ="Relocate"  CausesValidation="True" />
			             </ItemTemplate> 
                     </asp:TemplateField>
                     <asp:TemplateField>
 			             <ItemTemplate>
			               <asp:ImageButton ID="ibClone" runat="server" ImageUrl="/Images/copy_paste.png" CommandName="Select"  ToolTip="Copy/Paste" AlternateText="Copy"   />
			             </ItemTemplate>  
			         <HeaderStyle Width="40px" />               
                     </asp:TemplateField>             
                     <asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" SortExpression="id" />
                     <asp:BoundField DataField="source_type" HeaderText="Source Type" SortExpression="inv_source_type" />
                     <asp:BoundField DataField="name" HeaderText="Name" SortExpression="name" />
                     <asp:BoundField DataField="supplier" HeaderText="Supplier" SortExpression="supplier" />
                     <asp:BoundField DataField="lot_id" HeaderText="Batch ID" SortExpression="lot_id" />
                     <asp:BoundField DataField="serial_no" HeaderText="Serial No." SortExpression="serial_no" />
                     <asp:BoundField DataField="out_order_id" HeaderText="Purchase Order Id" SortExpression="out_order_id" />
                     <asp:BoundField DataField="purchase_order" HeaderText="PO Number to Supplier" SortExpression="purchase_order" />
                     <asp:BoundField DataField="in_order_id" HeaderText="Sales Order Id" SortExpression="in_order_id" />
                     <asp:BoundField DataField="sales_order" HeaderText="PO Number from Client" SortExpression="sales_order" />
                     <asp:BoundField DataField="original_quantity" HeaderText="Original Quantity" SortExpression="original_quantity" DataFormatString="{0:N0}"/>
                     <asp:BoundField DataField="actual_quantity" HeaderText="Actual Quantity" SortExpression="actual_quantity" DataFormatString="{0:N0}"/>
                     <asp:BoundField DataField="location_id" HeaderText="Location" SortExpression="location_id"/>
                     <asp:BoundField DataField="uom" HeaderText="Uom" SortExpression="uom" />
                     <asp:BoundField DataField="manufacture_date" HeaderText="Manufacture Date" SortExpression="manufacture_date" DataFormatString="{0:d}"/>
                     <asp:BoundField DataField="expiration_date" HeaderText="Expiration Date" SortExpression="expiration_date" DataFormatString="{0:d}"/>
                     <asp:BoundField DataField="arrive_date" HeaderText="Arrive Date" SortExpression="arrive_date" DataFormatString="{0:d}"/>
                     <asp:BoundField DataField="recorder" HeaderText="Recorded by" SortExpression="recorder" />
                     <asp:BoundField DataField="contact" HeaderText="Contact" SortExpression="contact" />
                     <asp:BoundField DataField="comment" HeaderText="comment" SortExpression="comment" />
                 </Columns>
                 <SelectedRowStyle  BackColor="#FFFFCC"/>
                 <BoundaryStyle BorderColor="Gray" BorderWidth="1px" BorderStyle="Solid"></BoundaryStyle>
                        <AlternatingRowStyle CssClass="GridAlternateRowStyle" />
                        <RowStyle CssClass="GridRowStyle" />
                </asp:CoolGridView>
                 <asp:Label ID="lblError1" runat="server" ForeColor="#FF3300" Height="60px" Width="350px"></asp:Label>
               </ContentTemplate>
              </asp:UpdatePanel> 
              
      <asp:SqlDataSource ID="sdsInventoryGrid" runat="server" 
           ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
           DeleteCommand="DELETE FROM `Inventory` WHERE `Inventory`.id=?" 
           ProviderName="System.Data.Odbc" 
       SelectCommand="
SELECT i.id, 
        i.source_type,
        p.name as name, 
        i.pd_or_mt_id,
   i.supplier_id,
   c.name as supplier,
   i.lot_id, 
  i.serial_no, 
  i.out_order_id, 
  o1.ponumber as purchase_order,
  i.in_order_id, 
  o.ponumber as sales_order,
  i.original_quantity, 
  i.actual_quantity,
  (select name from location where id = i.location_id) as location_id,
  (select i.location_id) as location,
    u.Name as uom,
  i.uom_id, 
  i.manufacture_date, 
  i.expiration_date, 
  i.arrive_date, 
  i.recorded_by,
  concat(e.firstname, ' ', e.lastname) as recorder,
  i.contact_employee, 
  concat(e1.firstname, ' ', e1.lastname) as contact,
  i.comment 
  FROM `inventory` i LEFT JOIN uom u ON i.uom_id = u.id 
   LEFT JOIN product p ON i.pd_or_mt_id = p.id
   LEFT JOIN client c ON i.supplier_id = c.id
   LEFT JOIN employee e ON i.recorded_by = e.id
   LEFT JOIN employee e1 ON e1.id = i.contact_employee
   LEFT JOIN `order_general` o  ON i.in_order_id = o.id 
   LEFT JOIN `order_general` o1 ON o1.id = i.out_order_id
 WHERE source_type = 'product'
 UNION
     SELECT i.id, 
        i.source_type,
        m.name as name, 
        i.pd_or_mt_id,
   i.supplier_id,
   c.name as supplier,
   i.lot_id, 
  i.serial_no, 
  i.out_order_id, 
  o1.ponumber as purchase_order,
  i.in_order_id, 
  o.ponumber as sales_order,
  i.original_quantity, 
  i.actual_quantity,
  (select name from location where id = i.location_id) as location_id,
  (select i.location_id) as location,
    u.Name as uom,
  i.uom_id, 
  i.manufacture_date,
  i.expiration_date, 
  i.arrive_date, 
  i.recorded_by,
  concat(e.firstname, ' ', e.lastname) as contact_name,
  i.contact_employee, 
  concat(e1.firstname, ' ', e1.lastname) as contact,
  i.comment 
  FROM `inventory` i LEFT JOIN uom u ON i.uom_id = u.id 
   LEFT JOIN material m ON i.pd_or_mt_id = m.id
   LEFT JOIN client c ON i.supplier_id = c.id
   LEFT JOIN employee e ON i.recorded_by = e.id
   LEFT JOIN employee e1 ON e1.id = i.contact_employee
   LEFT JOIN `order_general` o  ON i.in_order_id = o.id 
   LEFT JOIN `order_general` o1 ON o1.id = i.out_order_id 
  WHERE source_type = 'material'"
     
      EnableCaching="false"> 
    </asp:SqlDataSource>
        
     <asp:Panel ID="RecordPanel" runat="server" ScrollBars="Auto" CssClass="detail" 
       style="margin-top: 19px;  height:500px; width:370px; display:none" HorizontalAlign="Left" >
   <asp:UpdatePanel ID="updateRecordPanel" runat="server" UpdateMode="Conditional">
   <ContentTemplate>
   <asp:Button id="btnShowPopup" runat="server" style="display:none" />
    <asp:ModalPopupExtender ID="ModalPopupExtender" runat="server" TargetControlID="btnShowPopup"
         BackgroundCssClass="modalBackground" PopupControlID="RecordPanel" 
        PopupDragHandleControlID="RecordPanel" Drag="True" DropShadow="True" >
        </asp:ModalPopupExtender>
        
       <asp:FormView ID="FormView1" runat="server" DataSourceID="sdsInventoryConfig"
       EnableTheming="True" Height="100px" 
       HorizontalAlign="Center" Width="100%" CssClass="detailgrid" DefaultMode="Insert" CellPadding="4" ForeColor="#333333" 
       >      
       </asp:FormView>
   
       <asp:SqlDataSource ID="sdsInventoryConfig" runat="server" 
       ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
       ProviderName="System.Data.Odbc"  InsertCommand="Insert"
       SelectCommand=" SELECT `inventory`.id, 
    `inventory`.source_type,
  `inventory`.pd_or_mt_id, 
  `inventory`.supplier_id,
    client.name as ClientName,
   `inventory`.supplier_id,
   `inventory`.lot_id, 
  `inventory`.serial_no, 
  `inventory`.out_order_id, 
  `inventory`.in_order_id, 
  `inventory`.original_quantity, 
  `inventory`.actual_quantity,
  `inventory`.location_id as location_id,
    uom.Name as uom,
  `inventory`.uom_id, 
  `inventory`.manufacture_date, 
  `inventory`.expiration_date, 
  `inventory`.arrive_date, 
  `inventory`.recorded_by,
  employee.firstname ||' '||employee.lastname as contact_name,
  `inventory`.contact_employee, 
  `inventory`.comment 
  FROM `inventory` left join uom on `inventory`.uom_id = uom.id 
   left join client on `inventory`.supplier_id = client.id
   left join employee on `inventory`.recorded_by = employee.id
   Where  `inventory`.id = ?" 
             
        >
       <SelectParameters>
           <asp:ControlParameter ControlID="gvTable" Name="vid" 
            PropertyName="SelectedValue" />
       </SelectParameters>
       </asp:SqlDataSource>
  
       <div class="footer">
          <asp:LinkButton ID="btnSubmit" runat="server" CausesValidation="True" 
            OnClick="btnSubmit_Click"  Text="Submit" />&nbsp;
          <asp:LinkButton ID="btnCancel" runat="server" 
           CausesValidation="False" CommandName="Cancel" OnClick="btnCancel_Click"
             Text="Cancel" />
        </div>
       <asp:Label ID="lblError" runat="server" ForeColor="#FF3300" 
                Height="60px" Width="350px"></asp:Label>
                  
      </ContentTemplate>
      </asp:UpdatePanel>
       </asp:Panel>  


         <asp:Panel ID="Panel1" runat="server" ScrollBars="Auto" CssClass="detail" 
       style="margin-top: 19px;  height:500px; width:370px; display:none" HorizontalAlign="Left" >
   <asp:UpdatePanel ID="UpdatePanel1" runat="server" UpdateMode="Conditional">
   <ContentTemplate>
   <asp:Button id="Button1" runat="server" style="display:none" />
    <asp:ModalPopupExtender ID="ModalPopupExtender1" runat="server" TargetControlID="Button1"
         BackgroundCssClass="modalBackground" PopupControlID="Panel1" 
        PopupDragHandleControlID="Panel1" Drag="True" DropShadow="True" >
        </asp:ModalPopupExtender>
        
       <asp:FormView ID="FormView2" runat="server" DataSourceID="SqlDataSource1"
       EnableTheming="True" Height="100px" 
       HorizontalAlign="Center" Width="100%" CssClass="detailgrid"  DefaultMode="Insert" CellPadding="4" ForeColor="#333333" 
       >
       </asp:FormView>
   
       <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
       ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
       ProviderName="System.Data.Odbc"  InsertCommand="Insert"
       SelectCommand=" SELECT `inventory`.id, 
    `inventory`.source_type,
  `inventory`.pd_or_mt_id, 
  `inventory`.supplier_id,
    client.name as ClientName,
   `inventory`.supplier_id,
   `inventory`.lot_id, 
  `inventory`.serial_no, 
  `inventory`.out_order_id, 
  `inventory`.in_order_id, 
  `inventory`.original_quantity, 
  `inventory`.actual_quantity,
  `inventory`.location_id as location_id,
    uom.Name as uom,
  `inventory`.uom_id, 
  `inventory`.manufacture_date, 
  `inventory`.expiration_date, 
  `inventory`.arrive_date, 
  `inventory`.recorded_by,
  employee.firstname ||' '||employee.lastname as contact_name,
  `inventory`.contact_employee, 
  `inventory`.comment 
  FROM `inventory` left join uom on `inventory`.uom_id = uom.id 
   left join client on `inventory`.supplier_id = client.id
   left join employee on `inventory`.recorded_by = employee.id
   Where  `inventory`.id = @inventoryId?" 
             
        >
      <SelectParameters>
            <asp:Parameter Name="inventoryId"  />
       </SelectParameters>
       </asp:SqlDataSource>
       
       <div class="footer">
          <asp:LinkButton ID="LinkButton1" runat="server" CausesValidation="True" 
            OnClick="btnSubmitRelo_Click"  Text="Submit" />&nbsp;
          <asp:LinkButton ID="LinkButton2" runat="server" 
           CausesValidation="False" CommandName="Cancel" OnClick="btnCancel_Click"
             Text="Cancel" />
        </div>      
      </ContentTemplate>
      </asp:UpdatePanel>
       </asp:Panel>
</asp:panel>
</asp:Content>
