<%@ Page Language="C#" MasterPageFile="../ConfigureModule.master" AutoEventWireup="true" CodeBehind="ProductCategoryConfig.aspx.cs" Inherits="ezMESWeb.Configure.ProductCategoryConfig" Title="Product Group Configuration -- ezOOM" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>

<asp:content ID="Content2" contentplaceholderid="head" runat="server"> 
    </asp:content> 

<asp:Content ID="Content1" runat="server" contentplaceholderid="ContentPlaceHolder1">
<asp:ToolkitScriptManager ID="ToolkitScriptManager1" runat="server" />
<asp:Button ID="btnInsert" runat="server" Text="Insert" Width="147px" OnClick="btn_Click"/> 
 <asp:panel id="pnlScroll" runat="server" width="85%" 
height="100%" scrollbars="Horizontal">              

   <asp:UpdatePanel ID="gvTablePanel" runat="server" UpdateMode="Conditional" >
            <ContentTemplate>
         <asp:GridView ID="gvTable" runat="server" Caption="Product Group Configuration" 
               CssClass="datagrid" GridLines="None" DataSourceID="sdsPDGRGrid" 
               EmptyDataText="No product currently available" 
               AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
               onselectedindexchanged="gvTable_SelectedIndexChanged" 
                DataKeyNames="id" AllowPaging="True"  AllowSorting="True" PageSize="10" 
               EnableTheming="False" onpageindexchanged="gvTable_PageIndexChanged"
             >
            <SelectedRowStyle  BackColor="#FFFFCC"/>
            <Columns>
                <asp:TemplateField>
			   <ItemTemplate>
			       <asp:LinkButton ID="btnViewDetails" runat="server" Text="Edit" CommandName="Select" />
			     </ItemTemplate>                 
                 </asp:TemplateField>
                 
                <asp:BoundField DataField="ID" HeaderText="id" ReadOnly="True" SortExpression="ID" />
                <asp:BoundField DataField="name" HeaderText="Name" SortExpression="name" />
                <asp:BoundField DataField="if_active" HeaderText="If Active" SortExpression="if_active" />
                <asp:BoundField DataField="description" HeaderText="Description" SortExpression="description" />
                <asp:BoundField DataField="default_location" HeaderText="Default Location" SortExpression="default_location" />
                <asp:BoundField DataField="no_products" HeaderText="No. of Products" SortExpression="no_products" />
                <asp:BoundField DataField="prefix" HeaderText="Prefix"  SortExpression="prefix" />
                <asp:BoundField DataField="surfix" HeaderText="Surfix" SortExpression="surfix" />  
                <asp:BoundField DataField="create_time" HeaderText="Created Time" SortExpression="create_time" />
                <asp:BoundField DataField="created_people" HeaderText="Created By" SortExpression="created_people" />
                <asp:BoundField DataField="comment" HeaderText="Comment" SortExpression="comment" />
                   	
			   </Columns>
                   </asp:GridView>
             </ContentTemplate>
              </asp:UpdatePanel> 
      
              
       <asp:SqlDataSource ID="sdsPDGRGrid" runat="server" 
           ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
           DeleteCommand="DELETE FROM product WHERE id=?" 
           ProviderName="System.Data.Odbc" 
           SelectCommand="SELECT pg.id AS ID, 
                                 pg.name, 
                                 pg.if_active,
                                 pg.description, 
                                 l.name as default_location,
                                 pg.default_location_id,
                                 count(pd.id) AS no_products, 
                                 pg.prefix, 
                                 pg.surfix,
                                 pg.create_time, 
                                 CONCAT(e.firstname, ' ', e.lastname) AS created_people,  
                                 pg.comment 
  FROM product_group pg
  LEFT JOIN product pd ON pd.pg_id = pg.id
  LEFT JOIN employee e
    ON e.id = pg.created_by
    LEFT JOIN location l
    ON l.id = pg.default_location_id
 GROUP BY pg.id, pg.name, pg.if_active, pg.prefix, pg.surfix, pg.create_time, pg.created_by, pg.description, pg.comment
 ORDER BY pg.id">
       </asp:SqlDataSource>
       
        <asp:Panel ID="RecordPanel" runat="server" ScrollBars="Auto" CssClass="detail" 
       style="margin-top: 19px;  height:500px; width:370px; display:none" HorizontalAlign="Left" >
   <asp:UpdatePanel ID="updateRecordPanel" runat="server" UpdateMode="Conditional">
   <ContentTemplate>
   <asp:Button id="btnShowPopup" runat="server" style="display:none" />
    <asp:ModalPopupExtender ID="ModalPopupExtender" runat="server" TargetControlID="btnShowPopup"
         BackgroundCssClass="modalBackground" PopupControlID="RecordPanel" 
        PopupDragHandleControlID="RecordPanel" Drag="True" DropShadow="True" >
        </asp:ModalPopupExtender>
        
         <asp:FormView ID="FormView1" runat="server" DataSourceID="sdsPDGRConfig"
       EnableTheming="True" Height="100px" HorizontalAlign="Center" Width="100%" CssClass="detailgrid" DefaultMode="Insert" CellPadding="4" ForeColor="#333333" 
       >      
       </asp:FormView>
          <asp:SqlDataSource ID="sdsPDGRConfig" runat="server" 
       ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
       EnableCaching="false"
       ProviderName="System.Data.Odbc" 
       SelectCommand="SELECT pg.name, 
                                 pg.if_active,  
                                 pg.description,
                                 pg.default_location_id,
                                 pg.prefix, 
                                 pg.surfix,
                                 pg.comment
  FROM product_group pg
  WHERE pg.id = ?" 
        >
        <SelectParameters>
           <asp:ControlParameter ControlID="gvTable" Name="vid" 
            PropertyName="SelectedValue" />
       </SelectParameters>
       
       </asp:SqlDataSource>
       
         <div class="footer">
          <asp:LinkButton ID="btnSubmit" runat="server" CausesValidation="True" 
            OnClick="btnSubmit_Click"  Text="Submit" />&nbsp;
          <asp:LinkButton ID="btnCancel" runat="server" 
           CausesValidation="False" CommandName="Cancel" OnClick="btnCancel_Click"
             Text="Cancel" />
       </div>
       <asp:Label ID="lblError" runat="server" ForeColor="#FF3300" 
                Height="60px" Width="350px"></asp:Label>
                               
      </ContentTemplate>
      </asp:UpdatePanel>
      </asp:Panel>
             </asp:panel> 
 
</asp:Content>
