<%@ Page Title="" Language="C#" MasterPageFile="../ConfigureModule.master" AutoEventWireup="true" CodeFile="ProductCategoryConfig.aspx.cs" Inherits="ezMESWeb.ProductCategoryConfig" %>

<script runat="server">

    protected void product_group_data_Selecting(object sender, SqlDataSourceSelectingEventArgs e)
    {

    }
</script>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table border="1" width="100%">
<tr>
<td class="style13" valign="top" style="background-image: url(Images/bg.gif); width: 769px;">
<h2 style="text-align: center">
    <span style="font-size: 16pt">Product Category Configuration Page</span></h2>
<asp:FormView 
        ID="FormView1" runat="server" DataSourceID="product_group_data" DataKeyNames="id" DefaultMode="Insert" 
                                            HorizontalAlign="Center" Width="407px" 
                                            onpageindexchanging="FormView1_PageIndexChanging" >
    <EditItemTemplate>
        name:
        <asp:Label ID="lblName" runat="server" Text='<%# Eval("name") %>'></asp:Label>
        <br />
        prefix:
        <asp:TextBox ID="prefixTextBox" runat="server" Text='<%# Bind("prefix") %>'></asp:TextBox><br />
        surfix:
        <asp:TextBox ID="surfixTextBox" runat="server" Text='<%# Bind("surfix") %>'></asp:TextBox><br />
        create_time:
        <asp:TextBox ID="create_timeTextBox" runat="server" 
            Text='<%# Bind("create_time") %>' ReadOnly="True"></asp:TextBox><br />
        created_by:
        <asp:TextBox ID="created_byTextBox" runat="server" 
            Text='<%# Bind("created_by") %>' ReadOnly="True"></asp:TextBox><br />
        description:
        <asp:TextBox ID="descriptionTextBox" runat="server" Text='<%# Bind("description") %>'></asp:TextBox><br />
        comment:
        <asp:TextBox ID="commentTextBox" runat="server" Text='<%# Bind("comment") %>'></asp:TextBox><br />
        <asp:LinkButton ID="UpdateButton" runat="server" CausesValidation="True" CommandName="Update"
            Text="Update"></asp:LinkButton>
        &nbsp;<asp:LinkButton ID="UpdateCancelButton" runat="server" CausesValidation="False" CommandName="Cancel"
            Text="Cancel"></asp:LinkButton>
        <asp:Label ID="idLabel1" runat="server" Text='<%# Eval("id") %>' 
            Visible="False" />
    </EditItemTemplate>
    <InsertItemTemplate>
        name:
        <asp:TextBox ID="nameTextBox" runat="server" Text='<%# Bind("name") %>' />
        <br />
        prefix:
        <asp:TextBox ID="prefixTextBox" runat="server" Text='<%# Bind("prefix") %>' />
        <br />
        surfix:
        <asp:TextBox ID="surfixTextBox" runat="server" Text='<%# Bind("surfix") %>' />
        <br />
        description:
        <asp:TextBox ID="descriptionTextBox" runat="server" 
            Text='<%# Bind("description") %>' />
        <br />
        comment:
        <asp:TextBox ID="commentTextBox" runat="server" Text='<%# Bind("comment") %>' />
        <br />
        <asp:LinkButton ID="InsertButton" runat="server" CausesValidation="True" 
            CommandName="Insert" Text="Insert" />
&nbsp;<asp:LinkButton ID="InsertCancelButton" runat="server" CausesValidation="False" 
            CommandName="Cancel" Text="Cancel" />
    </InsertItemTemplate>
    <ItemTemplate>
        name:
        <asp:Label ID="nameLabel" runat="server" Text='<%# Bind("name") %>'></asp:Label><br />
        prefix:
        <asp:Label ID="prefixLabel" runat="server" 
            Text='<%# Bind("prefix") %>'></asp:Label>
        <br />
        surfix:
        <asp:Label ID="surfixLabel" runat="server" Text='<%# Bind("surfix") %>'></asp:Label>
        <asp:Label ID="state_changed_byLabel" runat="server" 
            Text='<%# Bind("state_changed_by") %>' />
        <br />
        description:
        <asp:Label ID="descriptionLabel" runat="server" 
            Text='<%# Bind("description") %>' />
        <br />
        comment:
        <asp:Label ID="commentLabel" runat="server" Text='<%# Bind("comment") %>'></asp:Label>
        <br />
        <asp:LinkButton ID="NewButton" runat="server" CausesValidation="False" CommandName="New"
            Text="New"></asp:LinkButton>
    </ItemTemplate>
    </asp:FormView>
    
    </td>

</tr>
<tr><td>
    <asp:SqlDataSource ID="product_group_data" runat="server"></asp:SqlDataSource>
    </td></tr>
<tr>
<td style="background-image: url(Images/bg.gif); width: 769px;">
View<br />
    &nbsp;<asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="id"
        DataSourceID="product_group_data" AutoGenerateDeleteButton="True" 
        AutoGenerateSelectButton="True" 
        onselectedindexchanged="GridView1_SelectedIndexChanged">
        <Columns>
            <asp:BoundField DataField="name" HeaderText="Name" 
                SortExpression="name" />
            <asp:BoundField DataField="prefix" HeaderText="Prefix" 
                SortExpression="prefix" />
            <asp:BoundField DataField="surfix" HeaderText="Surfix" 
                SortExpression="surfix" />
            <asp:BoundField DataField="create_time" HeaderText="Create Time" 
                SortExpression="create_time" />
            <asp:BoundField DataField="created_by" HeaderText="Created By" 
                SortExpression="created_by" />
            <asp:BoundField DataField="description" HeaderText="Description" 
                SortExpression="description" />
            <asp:BoundField DataField="comment" HeaderText="Comment" 
                SortExpression="comment" />
            <asp:BoundField DataField="id" HeaderText="id" Visible="False" />
        </Columns>
        <SelectedRowStyle BackColor="#666699" />
    </asp:GridView>
</td>
</tr>
</table>

    <br />

</asp:Content>

