<%@ Page Language="C#" MasterPageFile="../ConfigureModule.Master" AutoEventWireup="true" CodeBehind="ProductAttributeConfig.aspx.cs" Inherits="ezMESWeb.Configure.ProductAttributeConfig" Title="Product Attributes -- ezOOM" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>



<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
 <script type="text/javascript" language="javascript">
     function showDropDown(source, txtName) {
         var sourceID = source.name;
         sourceID = sourceID.replace(/\$/g, '_');
         sourceID = sourceID.substring(0, sourceID.length - 10);
         var sourceID = sourceID + 'lbl' + txtName;

         var strData = source.options[source.selectedIndex].value;
         var nIndex = strData.indexOf("||");
         strData = strData.substring(nIndex + 2);

         var lblRestriction = document.getElementById(sourceID);
         lblRestriction.innerHTML = strData;
     }
 </script>
<asp:ToolkitScriptManager ID="ToolkitScriptManager1" runat="server" />
<table border = 0><tr><td class="style19">Product:</td><td><asp:DropDownList ID="dpProduct" 
        runat="server" Width="300px" Height="30px" AutoPostBack="True" onselectedindexchanged="dpProd_SelectedIndexChanged">
    </asp:DropDownList></td></tr>
    <tr><td colspan =2>&nbsp;</td></tr>
<tr><td colspan=2><asp:Button ID="btnInsert" runat="server" Text="Add Attribute" Width="147px" OnClick="btn_Click"/> </tr>
 </table>              
<table style="width: 100%; height: 423px; margin-right: 0px; margin-top: 0px; border : 2px solid #6FBD06; ">
      <tr>
         <td style="height: 117px; width: 353px;">
   <asp:UpdatePanel ID="gvTablePanel" runat="server" UpdateMode="Conditional">
            <ContentTemplate>
            <asp:GridView ID="gvTable" runat="server" Caption="Product Attributes" 
               CssClass="datagrid" GridLines="None" DataSourceID="sdsProductAttributeConfigGrid" 
                EmptyDataText="This product does not have attribute" Height="80px" Width="500px"
               AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
               onselectedindexchanged="gvTable_SelectedIndexChanged" DataKeyNames="attr_id, parent_id" AllowPaging="True"  AllowSorting="True" PageSize="15" 
               EnableTheming="False" onpageindexchanged="gvTable_PageIndexChanged" >
                <Columns>
                    <asp:TemplateField><ItemTemplate>
                    <asp:LinkButton ID="btnViewDetails" runat="server" Text="Edit" CommandName="Select" />
                    </ItemTemplate></asp:TemplateField>

                    <asp:BoundField DataField="attr_name" HeaderText="Attribute Name"  SortExpression="attr_name" />
                    <asp:BoundField DataField="attr_value" HeaderText="Value"  SortExpression="attr_value" />
                    <asp:BoundField DataField="recorder_name" HeaderText="Recorder by" SortExpression="recorder_name" />
                    <asp:BoundField DataField="comment" HeaderText="Comment" SortExpression="comment" />
                </Columns>
                <SelectedRowStyle  BackColor="#FFFFCC"/>
             </asp:GridView>
             </ContentTemplate>
              </asp:UpdatePanel> 
              
       <asp:SqlDataSource ID="sdsProductAttributeConfigGrid" runat="server" 
           ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
           DeleteCommand="DELETE FROM `attribute_value` WHERE attr_id=? AND parent_id=?" 
           ProviderName="System.Data.Odbc" 
       SelectCommand="SELECT 
            T4.name AS product_name,
            T1.attr_id,
            T1.attr_name,
            T2.attr_value,
            T2.recorder,
            CONCAT(T3.firstname, ' ', T3.lastname) AS recorder_name,
            CONCAT('Data type: ', REPLACE(T1.data_type, 'varchar', 'text'), ' ',
            IF(T1.enum_values IS NULL,
            CONCAT(IF(T1.min_value IS NULL, '', CONCAT(' Min=', T1.min_value)), IF(T1.max_value IS NULL, '', CONCAT(' Max=', T1.max_value))),
            CONCAT('Value can only be one of the following:', T1.enum_values))) AS restriction,
            T2.comment,
           T2.parent_id
        FROM attribute_definition AS T1
        JOIN attribute_value AS T2
            ON T1.attr_id = T2.attr_id
              AND T1.attr_parent_type = 'product'
        JOIN product AS T4
           ON T4.id=T2.parent_id
        LEFT JOIN employee AS T3
            ON T3.id = T2.recorder
        WHERE T2.parent_id=?">
        <SelectParameters>
            <asp:ControlParameter ControlID="dpProduct" DefaultValue="0" Name="prodid" PropertyName="SelectedValue" />
        </SelectParameters>

        </asp:SqlDataSource>
        
        <asp:Panel ID="RecordPanel" runat="server" ScrollBars="Auto" CssClass="detail" 
       style="margin-top: 19px;  height:500px; width:330px; display:none" HorizontalAlign="Left" >
   <asp:UpdatePanel ID="updateRecordPanel" runat="server" UpdateMode="Conditional">
   <ContentTemplate>
   <asp:Button id="btnShowPopup" runat="server" style="display:none" />
    <asp:ModalPopupExtender ID="ModalPopupExtender" runat="server" TargetControlID="btnShowPopup"
         BackgroundCssClass="modalBackground" PopupControlID="RecordPanel" 
        PopupDragHandleControlID="RecordPanel" Drag="True" DropShadow="True" >
        </asp:ModalPopupExtender>
        
       <asp:FormView ID="FormView1" runat="server" DataSourceID="sdsProductAttributeConfig"
       EnableTheming="True" Height="100px" 
       HorizontalAlign="Center" Width="100%" CssClass="detailgrid" DefaultMode="Insert" CellPadding="4" ForeColor="#333333" >      
       </asp:FormView>
       
       <asp:SqlDataSource ID="sdsProductAttributeConfig" runat="server" 
       ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
       ProviderName="System.Data.Odbc"  
       SelectCommand="SELECT
            T4.name AS product_name,
            T1.attr_id,
            T1.attr_name,
            T2.attr_value,
            T2.recorder,
            CONCAT(T3.firstname, ' ', T3.lastname) AS recorder_name,
            CONCAT('Data type: ', REPLACE(T1.data_type, 'varchar', 'text'), ' ',
            IF(T1.enum_values IS NULL,
            CONCAT(IF(T1.min_value IS NULL, '', CONCAT(' Min=', T1.min_value)), IF(T1.max_value IS NULL, '', CONCAT(' Max=', T1.max_value))),
            CONCAT('Value can only be one of the following:', T1.enum_values))) AS restriction,
            T2.comment,
            T2.parent_id
       FROM attribute_definition AS T1
        JOIN attribute_value AS T2
            ON T1.attr_id = T2.attr_id
              AND T1.attr_parent_type = 'product'
        JOIN product AS T4
           ON T4.id=T2.parent_id
        LEFT JOIN employee AS T3
            ON T3.id = T2.recorder
        WHERE T2.parent_id=? AND T2.attr_id=?">
         <SelectParameters>
            <asp:ControlParameter ControlID="dpProduct" DefaultValue="0" Name="prodid" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="gvTable" Name="vid" PropertyName="SelectedValue" Type="int32" />
            
       </SelectParameters>
       </asp:SqlDataSource>
       
       <div class="footer">
          <asp:LinkButton ID="btnSubmit" runat="server" CausesValidation="True" 
            OnClick="btnSubmit_Click"  Text="Submit" />&nbsp;
          <asp:LinkButton ID="btnCancel" runat="server" 
           CausesValidation="False" CommandName="Cancel" OnClick="btnCancel_Click" Text="Cancel" />
       </div>
       <asp:Label ID="lblError" runat="server" ForeColor="#FF3300" Height="60px" Width="350px"></asp:Label>
                  
      </ContentTemplate>
      </asp:UpdatePanel>
       </asp:Panel>  
 
      </td>
       </tr>
       <tr>
        <td style="width: 353px">
           &nbsp;</td>
        </tr>               
  </table>
    
</asp:Content>
