<%@ Page Language="C#" MasterPageFile="../ConfigureModule.Master" AutoEventWireup="true" CodeBehind="ProdProcConfig.aspx.cs" Inherits="ezMESWeb.Configure.ProdProcConfig" Title="Product Process Association -- ezOOM" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>



<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

<asp:ToolkitScriptManager ID="ToolkitScriptManager1" runat="server" />
<table border = 0><tr><td class="style19">Product:</td><td><asp:DropDownList ID="dpProduct" 
        runat="server" Width="168px" Height="30px" AutoPostBack="True" 
        onselectedindexchanged="dpProd_SelectedIndexChanged">
    </asp:DropDownList></td></tr>
    <tr><td colspan =2>&nbsp;</td></tr>
<tr><td colspan=2><asp:Button ID="btnInsert" runat="server" Text="Add Workflow" 
        Width="147px" OnClick="btn_Click"/> </tr>
 </table>              
<table style="width: 100%; height: 423px; margin-right: 0px; margin-top: 0px; border : 2px solid #6FBD06; ">
      <tr>
         <td style="height: 117px; width: 353px;">
   <asp:UpdatePanel ID="gvTablePanel" runat="server" UpdateMode="Conditional">
            <ContentTemplate>
            <asp:GridView ID="gvTable" runat="server" Caption="Document(s) Related to Client" 
               CssClass="datagrid" GridLines="None" DataSourceID="sdsClientDocConfigGrid" 
               EmptyDataText="No workflow currently available for this product" Height="145px" Width="500px"
               AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
               onselectedindexchanged="gvTable_SelectedIndexChanged"  
                    DataKeyNames="process_id" AllowPaging="True"  AllowSorting="True" PageSize="15" 
               EnableTheming="False" onpageindexchanged="gvTable_PageIndexChanged"
             >
                <Columns>
                  <asp:TemplateField><ItemTemplate>
			       <asp:LinkButton ID="btnViewDetails" runat="server" Text="Edit" CommandName="Select" />
			     </ItemTemplate></asp:TemplateField>

                    <asp:BoundField DataField="process_name" HeaderText="Workflow"  
                        SortExpression="process_name" />
                    <asp:BoundField DataField="priority_name" HeaderText="Priority"  
                        SortExpression="priority_name" />
                    <asp:BoundField DataField="recorder_name" HeaderText="Recorder by" SortExpression="recorder_name" />
                    <asp:BoundField DataField="comment" HeaderText="Comment" 
                        SortExpression="comment" />
                </Columns>
                <SelectedRowStyle  BackColor="#FFFFCC"/>
             </asp:GridView>
             </ContentTemplate>
              </asp:UpdatePanel> 
              
       <asp:SqlDataSource ID="sdsClientDocConfigGrid" runat="server" 
           ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
           DeleteCommand="DELETE FROM `product_process` WHERE process_id=?" 
           ProviderName="System.Data.Odbc" 
       SelectCommand=" 
SELECT pp.process_id,
       pc.name as process_name,
       pp.priority,
       pr.name as priority_name,
       pp.recorder,
       concat(e.firstname, ' ', e.lastname) as recorder_name,
       pp.comment
  FROM product_process pp
LEFT JOIN process pc ON pc.id = pp.process_id
LEFT JOIN priority pr ON pr.id = pp.priority
LEFT JOIN employee e ON e.id = pp.recorder
 WHERE pp.product_id = ?"     
       >
           <SelectParameters>
               <asp:ControlParameter ControlID="dpProduct" DefaultValue="0" Name="prodid" 
                   PropertyName="SelectedValue" />
           </SelectParameters>

        </asp:SqlDataSource>
        
        <asp:Panel ID="RecordPanel" runat="server" ScrollBars="Auto" CssClass="detail" 
       style="margin-top: 19px;  height:500px; width:330px; display:none" HorizontalAlign="Left" >
   <asp:UpdatePanel ID="updateRecordPanel" runat="server" UpdateMode="Conditional">
   <ContentTemplate>
   <asp:Button id="btnShowPopup" runat="server" style="display:none" />
    <asp:ModalPopupExtender ID="ModalPopupExtender" runat="server" TargetControlID="btnShowPopup"
         BackgroundCssClass="modalBackground" PopupControlID="RecordPanel" 
        PopupDragHandleControlID="RecordPanel" Drag="True" DropShadow="True" >
        </asp:ModalPopupExtender>
        
       <asp:FormView ID="FormView1" runat="server" DataSourceID="sdsClientDocConfig"
       EnableTheming="True" Height="100px" 
       HorizontalAlign="Center" Width="100%" CssClass="detailgrid" DefaultMode="Insert" CellPadding="4" ForeColor="#333333" 
       >      
       </asp:FormView>
       
       <asp:SqlDataSource ID="sdsClientDocConfig" runat="server" 
       ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
       ProviderName="System.Data.Odbc"  
       SelectCommand="SELECT pp.process_id,
       pc.name as process_name,
       pp.priority,
       pp.comment
  FROM product_process pp
LEFT JOIN process pc ON pc.id = pp.process_id
WHERE pp.product_id = ? AND pp.process_id = ?" 
        >
         <SelectParameters>
            <asp:ControlParameter ControlID="dpProduct" DefaultValue="0" Name="prodid" 
                   PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="gvTable" Name="vid" 
            PropertyName="SelectedValue" Type="int32" />
            
       </SelectParameters>
       </asp:SqlDataSource>
       
       <div class="footer">
          <asp:LinkButton ID="btnSubmit" runat="server" CausesValidation="True" 
            OnClick="btnSubmit_Click"  Text="Submit" />&nbsp;
          <asp:LinkButton ID="btnCancel" runat="server" 
           CausesValidation="False" CommandName="Cancel" OnClick="btnCancel_Click"
             Text="Cancel" />
       </div>
       <asp:Label ID="lblError" runat="server" ForeColor="#FF3300" 
                Height="60px" Width="350px"></asp:Label>
                  
      </ContentTemplate>
      </asp:UpdatePanel>
       </asp:Panel>  
 
      </td>
       </tr>
       <tr>
        <td style="width: 353px">
           &nbsp;</td>
        </tr>               
  </table>
    
</asp:Content>
