<%@ Page Language="C#" MasterPageFile="../ConfigureModule.master" AutoEventWireup="true" CodeBehind="ProductConfig.aspx.cs" Inherits="ezMESWeb.Configure.ProductConfig" Title="Product Configuration -- ezOOM"
 %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>

<asp:content ID="Content2" contentplaceholderid="head" runat="server"> 
    </asp:content> 

<asp:Content ID="Content1" runat="server" contentplaceholderid="ContentPlaceHolder1">
<asp:ToolkitScriptManager ID="ToolkitScriptManager1" runat="server" />
<asp:Button ID="btnInsert" runat="server" Text="Insert" Width="147px" OnClick="btn_Click"/> 
 <asp:panel id="pnlScroll" runat="server" width="85%" 
height="100%" scrollbars="Horizontal">              

   <asp:UpdatePanel ID="gvTablePanel" runat="server" UpdateMode="Conditional" >
            <ContentTemplate>
         <asp:GridView ID="gvTable" runat="server" Caption="Product Configuration" 
               CssClass="datagrid" GridLines="None" DataSourceID="sdsPDGrid" 
               EmptyDataText="No product currently available" 
               AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
               onselectedindexchanged="gvTable_SelectedIndexChanged" 
                DataKeyNames="id" AllowPaging="True"  AllowSorting="True" PageSize="10" 
               EnableTheming="False" onpageindexchanged="gvTable_PageIndexChanged"
             >
            <SelectedRowStyle  BackColor="#FFFFCC"/>
            <Columns>
                <asp:TemplateField>
			   <ItemTemplate>
			       <asp:LinkButton ID="btnViewDetails" runat="server" Text="Edit" CommandName="Select" />
			     </ItemTemplate>                 
                 </asp:TemplateField>
                 
                <asp:BoundField DataField="ID" HeaderText="id" ReadOnly="True" SortExpression="ID" />
                <asp:BoundField DataField="product_group" HeaderText="Product Group" SortExpression="product_group" />
                <asp:BoundField DataField="name" HeaderText="Name" SortExpression="name" />
                <asp:BoundField DataField="version" HeaderText="Version" SortExpression="version" />
                <asp:BoundField DataField="lot_size" HeaderText="Lot Size" DataFormatString={0:N0} SortExpression="lot_size" />
                <asp:BoundField DataField="uom" HeaderText="Unit" SortExpression="uom" />
                <asp:BoundField DataField="lifespan" HeaderText="LifeSpan (days)" SortExpression="lifespan" />
               <asp:HyperLinkField DataNavigateUrlFields="id" 
                DataNavigateUrlFormatString="ProdProcConfig.aspx?prodid={0}" 
                DataTextField="num_process" DataTextFormatString="{0}" HeaderText="Num of Workflow(s)" />   
                <asp:BoundField DataField="create_time" HeaderText="Created Time" SortExpression="create_time" />
                <asp:BoundField DataField="created_people" HeaderText="Created By" SortExpression="created_people" />
                <asp:BoundField DataField="state_change_time" HeaderText="State Change Time" SortExpression="state_change_time" />
                <asp:BoundField DataField="updated_by" HeaderText="Updated By" SortExpression="updated_by" />
                <asp:BoundField DataField="description" HeaderText="Description" SortExpression="description" />
                <asp:BoundField DataField="comment" HeaderText="Comment" SortExpression="comment" />
                <asp:TemplateField>
                <ItemTemplate>
                    <input type="button" style="width:80px;height:30px"  onclick="location.href='ProductAttributeConfig.aspx?prodid=<%#Eval("id")%>'" value="Attribute" />
                </ItemTemplate>
                </asp:TemplateField>
			   </Columns>
                   </asp:GridView>
             </ContentTemplate>
              </asp:UpdatePanel> 
      
              
       <asp:SqlDataSource ID="sdsPDGrid" runat="server" 
           ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
           DeleteCommand="DELETE FROM product WHERE id=?" 
           ProviderName="System.Data.Odbc" 
           SelectCommand="select p.id as ID, p.pg_id, pg.name as product_group, p.name, 
           p.version, p.state, p.lot_size, p.uomid, uom.Name as uom, if(p.lifespan>0, p.lifespan, null) as lifespan,
           (select count(*) from product_process pp where pp.product_id = p.id) as num_process,
           p.create_time, p.created_by, concat(e.firstname, ' ', e.lastname) as created_people, p.state_change_time, concat(e2.firstname, ' ', e2.lastname) as updated_by, p.description, p.comment 
from product p left join product_group pg on p.pg_id =  pg.id
left join employee e on (p.created_by = e.id)
left join employee e2 on (p.state_changed_by = e2.id) 
left join uom on (uom.id = p.uomid)
order by p.id">
       </asp:SqlDataSource>
       
        <asp:Panel ID="RecordPanel" runat="server" ScrollBars="Auto" CssClass="detail" 
       style="margin-top: 19px;  height:500px; width:370px; display:none" HorizontalAlign="Left" >
   <asp:UpdatePanel ID="updateRecordPanel" runat="server" UpdateMode="Conditional">
   <ContentTemplate>
   <asp:Button id="btnShowPopup" runat="server" style="display:none" />
    <asp:ModalPopupExtender ID="ModalPopupExtender" runat="server" TargetControlID="btnShowPopup"
         BackgroundCssClass="modalBackground" PopupControlID="RecordPanel" 
        PopupDragHandleControlID="RecordPanel" Drag="True" DropShadow="True" >
        </asp:ModalPopupExtender>
        
         <asp:FormView ID="FormView1" runat="server" DataSourceID="sdsPDConfig"
       EnableTheming="True" Height="100px" HorizontalAlign="Center" Width="100%" CssClass="detailgrid" DefaultMode="Insert" CellPadding="4" ForeColor="#333333" 
       >      
       </asp:FormView>
          <asp:SqlDataSource ID="sdsPDConfig" runat="server" 
       ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
       EnableCaching="false"
       ProviderName="System.Data.Odbc" 
       SelectCommand="Select  
       p.pg_id, p.name, p.version, p.state, p.lot_size, p.uomid,
  if(p.lifespan>0, p.lifespan, null) as lifespan, p.create_time, p.created_by, p.state_change_time, p.state_changed_by,
  p.description, p.comment From product p, uom, employee, product_group
   where p.uomid = uom.id and 
   p.created_by = employee.id and 
   p.pg_id = `product_group`.id and p.id = ?" 
        >
        <SelectParameters>
           <asp:ControlParameter ControlID="gvTable" Name="vid" 
            PropertyName="SelectedValue" />
       </SelectParameters>
       
       </asp:SqlDataSource>
       
         <div class="footer">
          <asp:LinkButton ID="btnSubmit" runat="server" CausesValidation="True" 
            OnClick="btnSubmit_Click"  Text="Submit" />&nbsp;
          <asp:LinkButton ID="btnCancel" runat="server" 
           CausesValidation="False" CommandName="Cancel" OnClick="btnCancel_Click"
             Text="Cancel" />
       </div>
       <asp:Label ID="lblError" runat="server" ForeColor="#FF3300" 
                Height="60px" Width="350px"></asp:Label>
                               
      </ContentTemplate>
      </asp:UpdatePanel>
      </asp:Panel>
             </asp:panel> 
 
</asp:Content>
