<%@ Page Language="C#" MasterPageFile="../ConfigureModule.master" AutoEventWireup="true" CodeBehind="ProductGroupConfig.aspx.cs" Inherits="ezMESWeb.ProductGroupConfig"
 %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>

<asp:content ID="Content2" contentplaceholderid="head" runat="server"> 
 <link rel="Stylesheet" href="/CSS/general.css" type="text/css" media="screen" /> 
 <link rel="stylesheet" href="/CSS/datagrid.css" type="text/css" media="screen" /> 
 <link rel="stylesheet" href="/CSS/detailgrid.css" type="text/css" media="screen" />  
</asp:content> 

<asp:Content ID="Content1" runat="server" contentplaceholderid="ContentPlaceHolder1">
<asp:ToolkitScriptManager ID="ToolkitScriptManager1" runat="server" />
<table style="width: 100%; height: 423px; margin-right: 0px; margin-top: 0px; border : 2px solid #6FBD06; ">
      <tr>
         <td style="height: 117px; width: 347px;">
           <asp:Button ID="btnInsert" runat="server" Text="Insert" Width="147px" /> 
           <asp:UpdatePanel ID="gridViewPanel" runat="server" UpdateMode="Conditional">
            <ContentTemplate>
             <asp:GridView ID="gvProductGroup" runat="server" Caption="Product Groups" 
               CssClass="datagrid" GridLines="None" DataSourceID="sdsPDGrid" 
               EmptyDataText="No product group currently available" Height="145px" Width="900px"
               AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
               onselectedindexchanged="gvProductGroup_SelectedIndexChanged"  
               DataKeyNames="id" AllowPaging="True"  AllowSorting="true" PageSize="15" EnableTheming="False" 
               onpageindexchanged="gvProductGroup_PageIndexChanged"
             >
             <Columns>
                <asp:TemplateField>
			   <ItemTemplate>
			       <asp:LinkButton ID="btnViewDetails" runat="server" Text="Edit" CommandName="Select" />
			     </ItemTemplate>
				 </asp:TemplateField>	
                <asp:BoundField DataField="id" HeaderText="Id" ReadOnly="True" 
                                    SortExpression="Id" />
                <asp:BoundField DataField="name" HeaderText="Name" SortExpression="Name" />
                <asp:BoundField DataField="prefix" HeaderText="Prefix" 
                                    SortExpression="Prefix" />
                <asp:BoundField DataField="surfix" HeaderText="Surfix" 
                                    SortExpression="Surfix" />
                <asp:BoundField DataField="create_time" HeaderText="Create Time" 
                                    SortExpression="CT" />
                <asp:BoundField DataField="created_by" HeaderText="Created By" 
                                    SortExpression="CB" />
                <asp:BoundField DataField="description" HeaderText="Description" 
                                    SortExpression="Description" />
                <asp:BoundField DataField="comment" HeaderText="Comment" 
                                    SortExpression="Comment" />
                   	
			   </Columns>
               <SelectedRowStyle  BackColor="#ffffcc"/>
                </asp:GridView>
               </ContentTemplate>
              </asp:UpdatePanel> 
       <asp:SqlDataSource ID="sdsPDGrid" runat="server" 
           ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
           DeleteCommand="DELETE FROM product_group WHERE id=@id" 
           ProviderName="<%$ ConnectionStrings:ezmesConnectionString.ProviderName %>" 
           SelectCommand="select p.id, name, prefix, surfix, create_time, concat(firstname, ' ', lastname) as created_by, description, p.comment from product_group p, employee e where p.created_by = e.id" 
           InsertCommand="insert into product_group (name, prefix, surfix, create_time, created_by, description, comment) values (@name, @prefix, @surfix, now(), 1, @description, @comment)">
       </asp:SqlDataSource>
       
       <asp:Panel ID="UpdateRecordPanel" runat="server" CssClass="detail" style="display:none"
              Height="263px" HorizontalAlign="Left" Width="349px">
       <asp:UpdatePanel ID="updPnlProductGroup" runat="server" UpdateMode="Conditional">
           <ContentTemplate>
           <asp:Button id="btnShowPopup" runat="server" style="display:none" />
           <asp:ModalPopupExtender ID="btnUpdate_ModalPopupExtender" runat="server" 
                 PopupControlID="UpdateRecordPanel" PopupDragHandleControlID="UpdateRecordPanel"
                 TargetControlID="btnShowPopup" CancelControlID="UpdateCancelButton" 
                   BackgroundCssClass="modalBackground" Drag="True" DropShadow="True">
             </asp:ModalPopupExtender>
                 &nbsp; &nbsp;
            <asp:FormView ID="fvUpdatePG" runat="server" BorderStyle="Groove" 
                 CssClass="detailgrid" BorderWidth="2px" Caption="Update selected product group:" 
                 DataKeyNames="id" DataSourceID="sdsPDFvUpdate" DefaultMode="Edit" Height="200px" 
                HorizontalAlign="Center" onitemupdated="fvUpdatePG_ItemUpdated" Width="100%">
                     <EditItemTemplate>
                     <table border="1">
                     <tr>
                        <td>
                         Id:
                         </td>
                         <td>
                         <asp:Label ID="idLabel1" runat="server" Text='<%# Eval("id") %>' />
                         </td>
                     </tr>
                     <tr>
                        <td>
                         Name:
                         </td>
                         <td><asp:TextBox ID="nameTextBox" runat="server" Text='<%# Bind("name") %>' /></td>
                     </tr>
                     <tr>
                         <td>Prefix:</td>
                         <td><asp:TextBox ID="prefixTextBox" runat="server" Text='<%# Bind("prefix") %>' /></td>
                     </tr>
                     <tr>
                         <td>Surfix:</td>
                         <td><asp:TextBox ID="surfixTextBox" runat="server" Text='<%# Bind("surfix") %>' /></td>
                     </tr>
                     <tr>
                         <td>Description:</td>
                         <td><asp:TextBox ID="descriptionTextBox" runat="server" 
                             Text='<%# Bind("description") %>' /></td>
                     </tr>
                     <tr>
                         <td>Comment:</td>
                         <td><asp:TextBox ID="commentTextBox" runat="server" Text='<%# Bind("comment") %>' /></td>
                     </tr>
                      </table>
                     </EditItemTemplate>
                 </asp:FormView>
                 <div class="footer">
                    <asp:LinkButton ID="UpdateButton" runat="server" CausesValidation="True" 
                      OnClick="BtnUpdate_Click" CommandName="Update" Text="Update" />&nbsp;
                    <asp:LinkButton ID="UpdateCancelButton" runat="server" 
                         CausesValidation="False" CommandName="Cancel" Text="Cancel" />
                 </div>
                 </ContentTemplate>
                 </asp:UpdatePanel>
             </asp:Panel>
             <asp:SqlDataSource ID="sdsPDFvUpdate" runat="server" 
                 ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
                 InsertCommand="insert into product_group (name, prefix, surfix, create_time, created_by, description, comment) values (@name, @prefix, @surfix, now(), 1, @description, @comment)" 
                 ProviderName="<%$ ConnectionStrings:ezmesConnectionString.ProviderName %>" 
                 SelectCommand="SELECT p.id,p. name, p.prefix, p.surfix, p.description, p.comment  FROM `product_group` p where p.id = @vid" 
                 UpdateCommand="UPDATE product_group SET name=@name, prefix=@prefix, surfix=@surfix, description=@description, comment=@comment WHERE id=@id">
                 <SelectParameters>
                     <asp:ControlParameter ControlID="gvProductGroup" Name="vid" 
                         PropertyName="SelectedValue" />
                 </SelectParameters>
             </asp:SqlDataSource>
  
 
  <asp:Panel   
   ID="InsertRecordPanel" runat="server" Height="263px" CssClass="detail" 
       style="margin-top: 19px; display:none" Width="349px" HorizontalAlign="Left" >
      
       <ContentTemplate>
       <asp:ModalPopupExtender ID="btnInsert_ModalPopupExtender" runat="server" TargetControlID="btnInsert"
         CancelControlID="InsertCancelButton" BackgroundCssClass="modalBackground" PopupControlID="InsertRecordPanel" 
        PopupDragHandleControlID="InsertRecordPanel" Drag="True" DropShadow="True" >
        </asp:ModalPopupExtender>
 
       <asp:FormView ID="fvProductGroup" runat="server" 
           BorderStyle="Groove" BorderWidth="2px" Caption="Insert new product group:" 
           DataKeyNames="id" DataSourceID="sdsPDGrid" 
           DefaultMode="Insert" EnableTheming="True" 
           Height="200px" HorizontalAlign="Center" Width="100%"  
           CssClass="detailgrid">
           <InsertItemTemplate>
             <table border="1">
              <tr>
               <td>
               Name:
               </td>
               <td>
               <asp:TextBox ID="nameTextBox" runat="server" Text='<%# Bind("name") %>' />
               </td>
              </tr>
              <tr>
               <td>
               Prefix:
               </td>
               <td>
               <asp:TextBox ID="prefixTextBox" runat="server" Text='<%# Bind("prefix") %>' />
               </td>
              </tr>
              <tr>
               <td>
               Surfix:
               </td>
               <td>
               <asp:TextBox ID="surfixTextBox" runat="server" Text='<%# Bind("surfix") %>' />
               </td>
              </tr>
              <tr>
               <td>
               Description:
               </td>
               <td>
               <asp:TextBox ID="descriptionTextBox" runat="server" 
                   Text='<%# Bind("description") %>' />
               </td>
               </tr>
               <tr>
                <td>
               Comment:
                </td>
                <td>
               <asp:TextBox ID="commentTextBox" runat="server" Text='<%# Bind("comment") %>' />
               </td>
               </tr>
              </table>            
           </InsertItemTemplate>
       </asp:FormView>
       <div class="footer">
          <asp:LinkButton ID="InsertButton" runat="server" CausesValidation="True" 
            OnClick="BtnInsert_Click" CommandName="Update" Text="Insert" />&nbsp;
          <asp:LinkButton ID="InsertCancelButton" runat="server" 
            CausesValidation="False" CommandName="Cancel" Text="Cancel" />
       </div>    
       </ContentTemplate>
   </asp:Panel>      
                    </td>
                </tr>

                 <tr>
                    <td style="width: 347px">
                        &nbsp;</td>
                </tr>               
            </table>

</asp:Content>
