<%@ Page Language="C#" MasterPageFile="../ConfigureModule.Master" AutoEventWireup="true" CodeBehind="UomConversionConfig.aspx.cs" Inherits="ezMESWeb.Configure.UomConversionConfig" Title="Uom Conversions Association -- ezOMM" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>


<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .style19
        {
            height: 35px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

<asp:ToolkitScriptManager ID="ToolkitScriptManager1" runat="server" />
<table border = 0><tr><td class="style19">From UoM:</td><td><asp:DropDownList ID="dpUom" 
        runat="server" Width="168px" Height="30px" AutoPostBack="True" 
        onselectedindexchanged="dpUom_SelectedIndexChanged">
    </asp:DropDownList></td></tr>
    <tr><td colspan =2>&nbsp;</td></tr>
<tr><td colspan=2><asp:Button ID="btnInsert" runat="server" Text="Add Conversion" 
        Width="147px" OnClick="btn_Click"/> </tr>
 </table>              
<table style="width: 100%; height: 423px; margin-right: 0px; margin-top: 0px; border : 2px solid #6FBD06; ">
      <tr>
         <td style="height: 117px; width: 353px;">
   <asp:UpdatePanel ID="gvTablePanel" runat="server" UpdateMode="Conditional">
            <ContentTemplate>
            <asp:GridView ID="gvTable" runat="server" Caption="Uom Conversions" 
               CssClass="datagrid" GridLines="None" DataSourceID="sdsUomConversionConfigGrid" 
               EmptyDataText="No conversion from this UoM is currently available" Height="145px" Width="500px"
               AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
                 
                    DataKeyNames="to_id" AllowPaging="True"  AllowSorting="True" PageSize="15" 
               EnableTheming="False" onpageindexchanged="gvTable_PageIndexChanged"
             >
                <Columns>

                    <asp:BoundField DataField="name" HeaderText="To Uom" 
                        SortExpression="name" />
                 <asp:BoundField DataField="method" HeaderText="Converting Method" 
                        SortExpression="method" />
                    <asp:BoundField DataField="constant" HeaderText="Converting Constant" SortExpression="constant" />
                    <asp:BoundField DataField="comment" HeaderText="Comment" 
                        SortExpression="comment" />
                </Columns>
                <SelectedRowStyle  BackColor="#FFFFCC"/>
             </asp:GridView>
             </ContentTemplate>
              </asp:UpdatePanel> 
              
       <asp:SqlDataSource ID="sdsUomConversionConfigGrid" runat="server" 
           ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
           DeleteCommand="DELETE FROM `uom_conversion` WHERE from_id=? and to_id=?" 
           ProviderName="System.Data.Odbc" 
       SelectCommand="  SELECT c.to_id,
                               u.name,
                               c.method,
                               c.constant,
                               c.comment
                           FROM uom_conversion c, uom u
                         WHERE c.from_id=? AND u.id=c.to_id"     
       InsertCommand="modify_client" InsertCommandType="StoredProcedure">
           <SelectParameters>
               <asp:ControlParameter ControlID="dpUom" DefaultValue="0" Name="uomid" 
                   PropertyName="SelectedValue" />
           </SelectParameters>

           <DeleteParameters>
               <asp:ControlParameter ControlID="dpUom" DefaultValue="0" Name="fromid" 
                   PropertyName="SelectedValue" />
           </DeleteParameters>

        </asp:SqlDataSource>
        
        <asp:Panel ID="RecordPanel" runat="server" ScrollBars="Auto" CssClass="detail" 
       style="margin-top: 19px;  height:500px; width:350px; display:none" HorizontalAlign="Left" >
   <asp:UpdatePanel ID="updateRecordPanel" runat="server" UpdateMode="Conditional">
   <ContentTemplate>
   <asp:Button id="btnShowPopup" runat="server" style="display:none" />
    <asp:ModalPopupExtender ID="ModalPopupExtender" runat="server" TargetControlID="btnShowPopup"
         BackgroundCssClass="modalBackground" PopupControlID="RecordPanel" 
        PopupDragHandleControlID="RecordPanel" Drag="True" DropShadow="True" >
        </asp:ModalPopupExtender>
        
       <asp:FormView ID="FormView1" runat="server" 
       EnableTheming="True" Height="100px" 
       HorizontalAlign="Center" Width="100%" CssClass="detailgrid" DefaultMode="Insert" CellPadding="4" ForeColor="#333333" 
       >      
       </asp:FormView>
       

       
       <div class="footer">
          <asp:LinkButton ID="btnSubmit" runat="server" CausesValidation="True" 
            OnClick="btnSubmit_Click"  Text="Submit" />&nbsp;
          <asp:LinkButton ID="btnCancel" runat="server" 
           CausesValidation="False" CommandName="Cancel" OnClick="btnCancel_Click"
             Text="Cancel" />
       </div>
       <asp:Label ID="lblError" runat="server" ForeColor="#FF3300" 
                Height="60px" Width="350px"></asp:Label>
                  
      </ContentTemplate>
      </asp:UpdatePanel>
       </asp:Panel>  
 
      </td>
       </tr>
       <tr>
        <td style="width: 353px">
           &nbsp;</td>
        </tr>               
  </table>
    
</asp:Content>
