
<%@ Page Language="C#" MasterPageFile="~/Configure/ConfigureModule.master" AutoEventWireup="true" CodeFile="LocationConfigure.aspx.cs" Inherits="ezMESWeb.Configure.LocationConfigure" Title="Untitled Page" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>

<asp:Content ID="Content2" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<asp:ToolkitScriptManager ID="ToolkitScriptManager1" runat="server" />
<table style="width: 100%; height: 423px; margin-right: 0px; margin-top: 0px; border : 2px solid #6FBD06; ">
      <tr>
         <td style="height: 117px; width: 353px;">
   <asp:UpdatePanel ID="gvTablePanel" runat="server" UpdateMode="Conditional">
            <ContentTemplate>
             <asp:GridView ID="gvTable" runat="server" Caption="Location" 
               CssClass="datagrid" GridLines="None" DataSourceID="sdsLocGrid" 
               EmptyDataText="No location currently available" Height="145px" Width="500px"
               AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
               onselectedindexchanged="gvTable_SelectedIndexChanged"  
               DataKeyNames="id" AllowPaging="True"  AllowSorting="True" PageSize="15" EnableTheming="False" 
               onpageindexchanged="gvTable_PageIndexChanged"
             >
             <Columns>
               <asp:TemplateField>
               <ItemTemplate>
			       <asp:LinkButton ID="btnViewDetails" runat="server" Text="Edit" CommandName="Select" />
			     </ItemTemplate>
				 </asp:TemplateField>	
              
                 <asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" SortExpression="id" />
                 <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
                 <asp:BoundField DataField="description" HeaderText="description" SortExpression="description" />
                 <asp:BoundField DataField="comment" HeaderText="comment" SortExpression="comment" />
                   	
			   </Columns>
               <SelectedRowStyle  BackColor="#FFFFCC"/>
                </asp:GridView>
               </ContentTemplate>
              </asp:UpdatePanel> 
              
       <asp:SqlDataSource ID="sdsLocGrid" runat="server" 
           ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
           DeleteCommand="DELETE FROM location WHERE id=@id" 
           ProviderName="<%$ ConnectionStrings:ezmesConnectionString.ProviderName %>" 
       SelectCommand="SELECT * FROM location" >
        </asp:SqlDataSource>
       <!-- Add insert/edit form later-->
        
        </td>
       </tr>
       <tr>
        <td style="width: 353px">
           &nbsp;</td>
        </tr>               
  </table>
</asp:Content>

