
<%@ Page Language="C#" MasterPageFile="~/Configure/ConfigureModule.master" AutoEventWireup="true" CodeBehind="LocationConfigure.aspx.cs" Inherits="ezMESWeb.Configure.LocationConfigure" Title= "Location Configuration -- ezOOM" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>
<%@ Register Assembly="IdeaSparx.CoolControls.Web" Namespace="IdeaSparx.CoolControls.Web" TagPrefix="asp" %>

<asp:Content ID="Content2" ContentPlaceHolderID="head" Runat="Server"></asp:Content>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:ToolkitScriptManager ID="ToolkitScriptManager1" runat="server" />
    <asp:Button ID="btnInsert" runat="server" Text="Insert Location" Width="147px" OnClick="btn_Click"/> 
    <br />
    <asp:panel id="pnlScroll" runat="server" width="100%" scrollbars="Horizontal"> 
    <asp:UpdatePanel ID="gvTablePanel" runat="server" UpdateMode="Conditional">
        <ContentTemplate>
            <%-- <table style="width: 100%; height: 423px; margin-right: 0px; margin-top: 0px; border : 2px solid #6FBD06; ">
                 <tr>
                 <td style="height: 117px; width: 353px;">--%>
                <table width=" 100%">
                    <tr style="height:30px;">
			            <td align="center">
				            <asp:label id="title" runat="server"><b>Inventories</b></asp:label>
                        </td>
                    </tr>
                </table> 
                 <asp:CoolGridView ID="gvTable" runat="server" Caption="" 
                   CssClass="GridStyle" GridLines="None" DataSourceID="sdsLocGrid" 
                   EmptyDataText="No location currently available" Height="480px" Width="1024px"
                   AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
                   onselectedindexchanged="gvTable_SelectedIndexChanged"  onselectedindexchanging="gvTable_SelectedIndexChanging"
                   DataKeyNames="id" FixHeaders="true" AllowPaging="True"  AllowSorting="True" PageSize="15" PagerStyle-BackColor="#f2e8da" PagerSettings-Mode="NumericFirstLast" AllowResizeColumn="true"
                   EnableTheming="False"
                   onpageindexchanged="gvTable_PageIndexChanged"
                 >
                     <Columns>
                       <asp:TemplateField>
                       <ItemTemplate>
			               <asp:LinkButton ID="btnViewDetails" runat="server" Text="Edit" CommandName="Select" />             
			             </ItemTemplate>
				         </asp:TemplateField>
                         <asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" SortExpression="id" Visible="false" />
                         <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
                         <asp:BoundField DataField="parent_loc_id" HeaderText="Parent Location Name[Id]" ReadOnly="True" SortExpression="parent_loc_id" Visible="true" />
                         <asp:BoundField DataField="adjacent_loc_id1" HeaderText="Adjacent Location1 Name[Id]" ReadOnly="True" SortExpression="adjacent_loc_id1" Visible="true" />
                         <asp:BoundField DataField="adjacent_loc_id2" HeaderText="Adjacent Location2 Name[Id]" ReadOnly="True" SortExpression="adjacent_loc_id2" Visible="true" />
                         <asp:BoundField DataField="adjacent_loc_id3" HeaderText="Adjacent Location3 Name[Id]" ReadOnly="True" SortExpression="adjacent_loc_id3" Visible="true" />
                         <asp:BoundField DataField="adjacent_loc_id4" HeaderText="Adjacent Location4 Name[Id]" ReadOnly="True" SortExpression="adjacent_loc_id4" Visible="true" />
                         <asp:BoundField DataField="contact_employee" HeaderText="Contact" ReadOnly="True" SortExpression="contact_employee" Visible="false" />
                         <asp:BoundField DataField="create_time" HeaderText="id" ReadOnly="True" SortExpression="create_time" Visible="false" />
                         <asp:BoundField DataField="update_time" HeaderText="id" ReadOnly="True" SortExpression="update_time" Visible="false" />
                         <asp:BoundField DataField="description" HeaderText="description" SortExpression="description" />
                         <asp:BoundField DataField="comment" HeaderText="comment" SortExpression="comment" />
			          </Columns>
                  <SelectedRowStyle  BackColor="#FFFFCC"/>
                 <BoundaryStyle BorderColor="Gray" BorderWidth="1px" BorderStyle="Solid"></BoundaryStyle>
                        <AlternatingRowStyle CssClass="GridAlternateRowStyle" />
                        <RowStyle CssClass="GridRowStyle" />
                  </asp:CoolGridView>
                  <%--</td>
                  </tr>
                  </table>--%>
             <asp:Label ID="lblError1" runat="server" ForeColor="#FF3300" Height="60px" Width="350px"></asp:Label>
         </ContentTemplate>
    </asp:UpdatePanel> 
              
    <asp:SqlDataSource ID="sdsLocGrid" runat="server" 
        ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
        DeleteCommand="DELETE FROM location WHERE id=?" 
        ProviderName="System.Data.Odbc" 
    SelectCommand="SELECT id,
        name,
        (select concat((select name from location where id = l1.parent_loc_id), '[', parent_loc_id, ']')) as parent_loc_id,
        (select concat((select name from location where id = l1.adjacent_loc_id1), '[', l1.adjacent_loc_id1, ']')) as adjacent_loc_id1,
        (select concat((select name from location where id = l1.adjacent_loc_id2), '[', l1.adjacent_loc_id2, ']')) as adjacent_loc_id2,
        (select concat((select name from location where id = l1.adjacent_loc_id3), '[', l1.adjacent_loc_id3, ']')) as adjacent_loc_id3,
        (select concat((select name from location where id = l1.adjacent_loc_id4), '[', l1.adjacent_loc_id4,']')) as adjacent_loc_id4,
        contact_employee,
        create_time,
        update_time,
        description,
        comment
        FROM location l1" >
    </asp:SqlDataSource>

    <asp:Panel ID="RecordPanel" runat="server" ScrollBars="Auto" CssClass="detail" style="margin-top: 19px;  height:500px; width:370px; display:none" HorizontalAlign="Left" >
        <asp:UpdatePanel ID="updateRecordPanel" runat="server" UpdateMode="Conditional">
        <ContentTemplate>
        <asp:Button id="btnShowPopup" runat="server" style="display:none" />
        <asp:ModalPopupExtender ID="ModalPopupExtender" runat="server" TargetControlID="btnShowPopup" BackgroundCssClass="modalBackground" PopupControlID="RecordPanel" PopupDragHandleControlID="RecordPanel" Drag="True" DropShadow="True" ></asp:ModalPopupExtender>
        <asp:FormView ID="FormView1" runat="server" DataSourceID="sdsLocInsert" EnableTheming="True" Height="100px" HorizontalAlign="Center" Width="100%" CssClass="detailgrid" DefaultMode="Insert" CellPadding="4" ForeColor="#333333" ></asp:FormView>        
              
        <asp:SqlDataSource ID="sdsLocInsert" runat="server" 
           ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
           ProviderName="System.Data.Odbc"  InsertCommand="Insert"
           SelectCommand=" SELECT *  FROM `location` Where  `location`.id = ?" >
          <SelectParameters>
              <asp:ControlParameter ControlID ="gvTable" PropertyName="SelectedValue"  />
          </SelectParameters>
        </asp:SqlDataSource>
       
        <div class="footer">
            <asp:LinkButton ID="LinkButton1" runat="server" CausesValidation="True" OnClick="btnSubmit_Click"  Text="Submit" />&nbsp;
            <asp:LinkButton ID="LinkButton2" runat="server" CausesValidation="False" CommandName="Cancel" OnClick="btnCancel_Click" Text="Cancel" />
        </div>
        <asp:Label ID="lblError" runat="server" ForeColor="#FF3300" Height="60px" Width="350px"></asp:Label>
        </ContentTemplate>
        </asp:UpdatePanel>
    </asp:Panel>
</asp:Panel>
</asp:Content>

