<%@ Page Language="C#" MasterPageFile="Main.Master" AutoEventWireup="true" CodeBehind="ConfigTemplate.aspx.cs" Inherits="ezMESWeb.ConfigTemplate"
 %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>

<asp:content ID="Content2" contentplaceholderid="head" runat="server"> 
 <link rel="Stylesheet" href="/CSS/general.css" type="text/css" media="screen" /> 
 <link rel="stylesheet" href="/CSS/datagrid.css" type="text/css" media="screen" /> 
 <link rel="stylesheet" href="/CSS/detailgrid.css" type="text/css" media="screen" />  
</asp:content> 

<asp:Content ID="Content1" runat="server" contentplaceholderid="ContentPlaceHolder1">
<asp:ToolkitScriptManager ID="ToolkitScriptManager1" runat="server" />
<table style="width: 100%; height: 423px; margin-right: 0px; margin-top: 0px; border : 2px solid #6FBD06; ">
      <tr>
         <td style="height: 117px; width: 347px;">
                     
             <asp:Button ID="btnInsert" runat="server" Text="Insert" Width="147px" /> 
             <asp:ModalPopupExtender ID="mdlPopup" runat="server" TargetControlID="btnInsert"
             BackgroundCssClass="modalBackground" PopupControlID="InsertPanel" 
              PopupDragHandleControlID="InsertPanel" Drag="True" DropShadow="True" >
             </asp:ModalPopupExtender>
 
           <asp:UpdatePanel ID="gvTablePanel" runat="server" UpdateMode="Conditional">
            <ContentTemplate>
             <asp:GridView ID="gvTable" runat="server" Caption="Product Groups" 
               CssClass="datagrid" GridLines="None" DataSourceID="sdsGridnInsertFv" 
               EmptyDataText="No product group currently available" Height="145px" Width="900px"
               AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
               onselectedindexchanged="gvTable_SelectedIndexChanged"  
               DataKeyNames="id" AllowPaging="True" PageSize="15" EnableTheming="False" onpageindexchanged="gvTable_PageIndexChanged"
             >
             <Columns>
                <asp:TemplateField>
			   <ItemTemplate>
			       <asp:LinkButton ID="btnViewDetails" runat="server" Text="Edit" CommandName="Select" />
			     </ItemTemplate>
				 </asp:TemplateField>	
                <asp:BoundField DataField="id" HeaderText="Id" ReadOnly="True" 
                                    SortExpression="Id" />
                <asp:BoundField DataField="name" HeaderText="Name" SortExpression="Name" />
                <asp:BoundField DataField="prefix" HeaderText="Prefix" 
                                    SortExpression="Prefix" />
                <asp:BoundField DataField="surfix" HeaderText="Surfix" 
                                    SortExpression="Surfix" />
                <asp:BoundField DataField="create_time" HeaderText="Create Time" 
                                    SortExpression="CT" />
                <asp:BoundField DataField="created_by" HeaderText="Created By" 
                                    SortExpression="CB" />
                <asp:BoundField DataField="description" HeaderText="Description" 
                                    SortExpression="Description" />
                <asp:BoundField DataField="comment" HeaderText="Comment" 
                                    SortExpression="Comment" />
                   	
			   </Columns>
               <SelectedRowStyle  BackColor="#ffffcc"/>
                </asp:GridView>
               </ContentTemplate>
              </asp:UpdatePanel> 
       <asp:SqlDataSource ID="sdsGridnInsertFv" runat="server" 
           ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
           DeleteCommand="DELETE FROM product_group WHERE id=@id" 
           ProviderName="System.Data.Odbc" 
           SelectCommand="select p.id, name, prefix, surfix, create_time, concat(firstname, ' ', lastname) as created_by, description, p.comment from product_group p, employee e where p.created_by = e.id" 
           
                 InsertCommand="insert into product_group (name, prefix, surfix, create_time, created_by, description, comment) values (@name, @prefix, @surfix, now(), 1, @description, @comment)">
       </asp:SqlDataSource>
       
        <asp:Panel ID="RecordPanel" runat="server" CssClass="detail" style="display:none"
              Height="300px" HorizontalAlign="Left" Width="350px">
       <asp:UpdatePanel ID="updateRecordPanel" runat="server" UpdateMode="Conditional">
           <ContentTemplate>
           <asp:Button id="btnShowPopup" runat="server" style="display:none" />
           <asp:ModalPopupExtender ID="ModalPopupExtender" runat="server" 
                 PopupControlID="UpdatePanel" PopupDragHandleControlID="UpdatePanel"
                 TargetControlID="btnShowPopup" 
                   BackgroundCssClass="modalBackground" Drag="True" DropShadow="True">
             </asp:ModalPopupExtender>
                 &nbsp; &nbsp;
            <asp:FormView ID="FormView1" runat="server" BorderStyle="Groove" 
                 CssClass="detailgrid" BorderWidth="2px" Caption="Update selected product group:" 
                 DataKeyNames="id" DataSourceID="sdsUpdate" DefaultMode="Edit" Height="200px" 
                HorizontalAlign="Center" onitemupdated="fvUpdate_ItemUpdated" Width="100%">
                     <EditItemTemplate>
                           <table border="1">
                           <tr><td>
                         id:
                         </td>
                         <td>
                         <asp:Label ID="idLabel" runat="server" Text='<%# Eval("id") %>' />
                         
                         <asp:TextBox ID="pg_idTextBox" runat="server" Text='<%# Eval("pg_id") %>' 
                             Visible="False"></asp:TextBox>
                         </td>
                      </tr>
                      <tr>
                        <td>
                         product_group:
                        </td>
                        <td><asp:DropDownList ID="ddProduct_group2" runat="server" 
                             DataSourceID="sdsProduct_group" DataTextField="name" DataValueField="id" 
                             Width="200px">
                         </asp:DropDownList>
                        </td>
                     </tr>
                     <tr>
                       <td>
                         name:
                       </td>
                       <td>
                         <asp:TextBox ID="nameTextBox" runat="server" Text='<%# Bind("name") %>' />
                       </td>
                     </tr>
                     <tr>
                       <td>
                         description:
                       </td>
                       <td>
                         <asp:TextBox ID="descriptionTextBox" runat="server" 
                             Text='<%# Bind("description") %>' />
                       </td>
                     </tr>
                     <tr>
                       <td>
                         comment:
                       </td>
                       <td>  
                     <asp:TextBox ID="commentTextBox" runat="server" Text='<%# Bind("comment") %>' />
                       </td>
                      </tr>
                      </table>
                         &nbsp;
                     </EditItemTemplate>
                     <InsertItemTemplate>
                         id:
                         <asp:TextBox ID="idTextBox" runat="server" Text='<%# Bind("id") %>' />
                         <br />
                         product_group:
                         <asp:TextBox ID="product_groupTextBox" runat="server" 
                             Text='<%# Bind("product_group") %>' />
                         <br />
                         name:
                         <asp:TextBox ID="nameTextBox" runat="server" Text='<%# Bind("name") %>' />
                         <br />
                         description:
                         <asp:TextBox ID="descriptionTextBox" runat="server" 
                             Text='<%# Bind("description") %>' />
                         <br />
                         comment:
                         <asp:TextBox ID="commentTextBox" runat="server" Text='<%# Bind("comment") %>' />
                         <br />
                         <asp:LinkButton ID="InsertButton" runat="server" CausesValidation="True" 
                             CommandName="Insert" Text="Insert" />
                         &nbsp;<asp:LinkButton ID="InsertCancelButton" runat="server" 
                             CausesValidation="False" CommandName="Cancel" Text="Cancel" />
                     </InsertItemTemplate>
                     <ItemTemplate>
                         id:
                         <asp:Label ID="idLabel1" runat="server" Text='<%# Eval("id") %>' />
                         <br />
                         product_group:
                         <asp:Label ID="product_groupLabel" runat="server" 
                             Text='<%# Bind("product_group") %>' />
                         <br />
                         name:
                         <asp:Label ID="nameLabel" runat="server" Text='<%# Bind("name") %>' />
                         <br />
                         description:
                         <asp:Label ID="descriptionLabel" runat="server" 
                             Text='<%# Bind("description") %>' />
                         <br />
                         comment:
                         <asp:Label ID="commentLabel" runat="server" Text='<%# Bind("comment") %>' />
                         <br />
                         <asp:LinkButton ID="EditButton" runat="server" CausesValidation="False" 
                             CommandName="Edit" Text="Edit" />
                         &nbsp;<asp:LinkButton ID="NewButton" runat="server" CausesValidation="False" 
                             CommandName="New" Text="New" />
                     </ItemTemplate>
                 </asp:FormView>
                 <div class="footer">
                    <asp:LinkButton ID="btnSubmitUpdate" runat="server" CausesValidation="True" 
                      OnClick="btnSubmitUpdate_Click" CommandName="Update" Text="Submit" />&nbsp;
                    <asp:LinkButton ID="btnCancelUpdate" runat="server" 
                         CausesValidation="False" CommandName="Cancel" OnClick="btnCancelUpdate_Click"
                         Text="Cancel" />
                 </div>
               <asp:Label ID="lblErrorUpdate" runat="server" ForeColor="#FF3300" 
                  Height="60px" Width="350px"></asp:Label>
                 </ContentTemplate>
                 </asp:UpdatePanel>
             </asp:Panel>
             <asp:SqlDataSource ID="sdsUpdate" runat="server" 
                 ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
                 InsertCommand="insert into product_group (name, prefix, surfix, create_time, created_by, description, comment) values (@name, @prefix, @surfix, now(), 1, @description, @comment)" 
                 ProviderName="System.Data.Odbc" 
                 SelectCommand="SELECT p.id,p. name, p.prefix, p.surfix, p.description, p.comment  FROM `product_group` p where p.id = @vid" 
                 
                 UpdateCommand="UPDATE product_group SET name=@name, prefix=@prefix, surfix=@surfix, description=@description, comment=@comment WHERE id=@id">
                 <SelectParameters>
                     <asp:ControlParameter ControlID="gvTable" Name="vid" 
                         PropertyName="SelectedValue" />
                 </SelectParameters>
             </asp:SqlDataSource>
  
             <asp:SqlDataSource ID="sdsProduct_group" runat="server" 
                 ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
                 ProviderName="System.Data.Odbc" 
                 SelectCommand="select id, name from product_group"></asp:SqlDataSource> 
  <asp:Panel   
   ID="InsertPanel" runat="server" Height="300px" CssClass="detail" 
                 style="display:none" Width="350px" 
                 HorizontalAlign="Left" >
             <asp:UpdatePanel ID="InsertBufferPanel" runat="server" UpdateMode="Conditional">          
 

          <ContentTemplate>

       <asp:Table ID="Table1" runat="server" BorderWidth="0" Width="100%" Height="238px">
           <asp:TableRow ID="TableRow1" runat="server">
               <asp:TableCell ID="TableCell1" runat="server" Height="30px" HorizontalAlign="Center">
                   Insert New Product
               </asp:TableCell>
           </asp:TableRow>
           <asp:TableRow ID="TableRow2" runat="server">
               <asp:TableCell ID="TableCell2" runat="server" HorizontalAlign="Center">
               <asp:Table ID="Table2" runat="server" CssClass="detailgrid">
                   <asp:TableRow ID="TableRow21" runat="server">
                       <asp:TableCell ID="TableCell21" runat="server" Height="25px" Width="30%">
                           Product Group:</asp:TableCell>
                       <asp:TableCell ID="TableCell22" runat="server" Height="25px" Width="70%" HorizontalAlign="Left">
                           <asp:DropDownList ID="ddProduct_group" runat="server" 
                               DataSourceID="sdsProduct_group" DataTextField="name" DataValueField="id" 
                               Height="25px" Width="166px">
                           </asp:DropDownList>
                       </asp:TableCell>
                   </asp:TableRow>
                   <asp:TableRow ID="TableRow22" runat="server">
                       <asp:TableCell ID="TableCell23" runat="server" Height="25px">
                           Name:</asp:TableCell>
                       <asp:TableCell ID="TableCell24" runat="server" Height="25px" HorizontalAlign="Left">
                           <asp:TextBox ID="nameTextBox" runat="server"></asp:TextBox>
                       </asp:TableCell>
                   </asp:TableRow>
                   <asp:TableRow  ID="TableRow23" runat="server">
                       <asp:TableCell ID="TableCell25" runat="server" Height="50px">
                           Description:</asp:TableCell>
                       <asp:TableCell ID="TableCell26" runat="server" Height="50px">
                           <asp:TextBox ID="descriptionTextBox" runat="server" Height="46px" 
                               TextMode="MultiLine" Width="230px"></asp:TextBox>
                       </asp:TableCell>
                   </asp:TableRow>
                   <asp:TableRow ID="TableRow24" runat="server">
                       <asp:TableCell ID="TableCell27" runat="server" Height="50px">
                           Comment:</asp:TableCell>
                       <asp:TableCell ID="TableCell28" runat="server" Height="50px">
                           <asp:TextBox ID="commentTextBox" runat="server" Height="41px" 
                               TextMode="MultiLine" Width="229px"></asp:TextBox>
                       </asp:TableCell>
                   </asp:TableRow>
               </asp:Table>
               </asp:TableCell>
           </asp:TableRow>
           <asp:TableRow ID="TableRow3" runat="server">
               <asp:TableCell ID="TableCell3" runat="server" HorizontalAlign="Center">
               <asp:LinkButton ID="btnSubmitInsert" runat="server" CausesValidation="False" CommandName="Insert" Text="Submit" onclick="btnSubmitInsert_Click" />    
               &nbsp;&nbsp;
               <asp:LinkButton ID="btnCancelInsert" runat="server" 
                         CausesValidation="False" CommandName="Cancel" Text="Cancel" onclick="btnCancelInsert_Click"/>
               
               </asp:TableCell>
           </asp:TableRow>
           </asp:Table> 
                        
 
               <asp:Label ID="lblErrorInsert" runat="server" ForeColor="#FF3300" 
                  Height="60px" Width="350px"></asp:Label>
               
           
       
          </ContentTemplate>
</asp:UpdatePanel>
   </asp:Panel>      
                    </td>
                </tr>

                 <tr>
                    <td style="width: 347px">
                        &nbsp;</td>
                </tr>               
            </table>

</asp:Content>
