<%@ Page Language="C#" MasterPageFile="../ConfigureModule.Master" AutoEventWireup="true" CodeBehind="ProcessSegmentConfig.aspx.cs" Inherits="ezMESWeb.Configure.ProcessSegmentConfig" Title="Process Segment Configuration -- ezOMM" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>



<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

<asp:ToolkitScriptManager ID="ToolkitScriptManager1" runat="server" />
<table border = 0><tr><td class="style19">Workflow:</td><td><asp:DropDownList ID="dpProcess" 
        runat="server" Width="300px" Height="30px" AutoPostBack="True" 
        onselectedindexchanged="dpProc_SelectedIndexChanged">
    </asp:DropDownList></td></tr>
    <tr><td colspan =2>&nbsp;</td></tr>
<tr><td colspan=2><asp:Button ID="btnInsert" runat="server" Text="Add Segment" 
        Width="147px" OnClick="btn_Click"/> </tr>
 </table>              
<table style="width: 100%; height: 423px; margin-right: 0px; margin-top: 0px; border : 2px solid #6FBD06; ">
      <tr>
         <td style="height: 117px; width: 353px;">
   <asp:UpdatePanel ID="gvTablePanel" runat="server" UpdateMode="Conditional">
            <ContentTemplate>
            <asp:GridView ID="gvTable" runat="server" Caption="Segments belong to Selected Workflow" 
               CssClass="datagrid" GridLines="None" DataSourceID="sdsClientDocConfigGrid" 
               EmptyDataText="No segment currently configured for this workflow." Height="145px" Width="500px"
               AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
               onselectedindexchanged="gvTable_SelectedIndexChanged"  
                    DataKeyNames="segment_id" AllowPaging="True"  AllowSorting="True" PageSize="15" 
               EnableTheming="False" onpageindexchanged="gvTable_PageIndexChanged"
             >
                <Columns>
                  <asp:TemplateField><ItemTemplate>
			       <asp:LinkButton ID="btnViewDetails" runat="server" Text="Edit" CommandName="Select" />
			     </ItemTemplate></asp:TemplateField>
                <asp:BoundField DataField="segment_id"   
                        SortExpression="segment_id" Visible=false />
                    <asp:BoundField DataField="name" HeaderText="Segment Name"  
                        SortExpression="name" />
                    <asp:BoundField DataField="position" HeaderText="Position"  
                        SortExpression="position" />    
                    <asp:BoundField DataField="description" HeaderText="Description" 
                        SortExpression="description" />
                </Columns>
                <SelectedRowStyle  BackColor="#FFFFCC"/>
             </asp:GridView>
             </ContentTemplate>
              </asp:UpdatePanel> 
              
       <asp:SqlDataSource ID="sdsClientDocConfigGrid" runat="server" 
           ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
           DeleteCommand="DELETE FROM `process_segment` WHERE process_id=? and segment_id=?" 
           ProviderName="System.Data.Odbc" 
       SelectCommand=" 
SELECT segment_id,
      name,
      position,
      description
   FROM process_segment 
 WHERE process_id = ? 
 ORDER BY position"     
       >
           <SelectParameters>
               <asp:ControlParameter ControlID="dpProcess" DefaultValue="0" Name="prodid" 
                   PropertyName="SelectedValue" />
           </SelectParameters>

           <DeleteParameters>
               <asp:ControlParameter ControlID="dpProcess" Name="procid" 
                   PropertyName="SelectedValue" />
           </DeleteParameters>

        </asp:SqlDataSource>
        
        <asp:Panel ID="RecordPanel" runat="server" ScrollBars="Auto" CssClass="detail" 
       style="margin-top: 19px;  height:500px; width:330px; display:none" HorizontalAlign="Left" >
   <asp:UpdatePanel ID="updateRecordPanel" runat="server" UpdateMode="Conditional">
   <ContentTemplate>
   <asp:Button id="btnShowPopup" runat="server" style="display:none" />
    <asp:ModalPopupExtender ID="ModalPopupExtender" runat="server" TargetControlID="btnShowPopup"
         BackgroundCssClass="modalBackground" PopupControlID="RecordPanel" 
        PopupDragHandleControlID="RecordPanel" Drag="True" DropShadow="True" >
        </asp:ModalPopupExtender>
        
       <asp:FormView ID="FormView1" runat="server" DataSourceID="sdsClientDocConfig"
       EnableTheming="True" Height="100px" 
       HorizontalAlign="Center" Width="100%" CssClass="detailgrid" DefaultMode="Insert" CellPadding="4" ForeColor="#333333" 
       >      
       </asp:FormView>
       
       <asp:SqlDataSource ID="sdsClientDocConfig" runat="server" 
       ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
       ProviderName="System.Data.Odbc"  
       SelectCommand="SELECT segment_id,
       name,
       position,
       description
  FROM process_segment
WHERE process_id = ? AND segment_id = ?" 
        >
         <SelectParameters>
            <asp:ControlParameter ControlID="dpProcess" DefaultValue="0" Name="prodid" 
                   PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="gvTable" Name="vid" 
            PropertyName="SelectedValue" Type="int32" />
            
       </SelectParameters>
       </asp:SqlDataSource>
       
       <div class="footer">
          <asp:LinkButton ID="btnSubmit" runat="server" CausesValidation="True" 
            OnClick="btnSubmit_Click"  Text="Submit" />&nbsp;
          <asp:LinkButton ID="btnCancel" runat="server" 
           CausesValidation="False" CommandName="Cancel" OnClick="btnCancel_Click"
             Text="Cancel" />
       </div>
       <asp:Label ID="lblError" runat="server" ForeColor="#FF3300" 
                Height="60px" Width="350px"></asp:Label>
                  
      </ContentTemplate>
      </asp:UpdatePanel>
       </asp:Panel>  
 
      </td>
       </tr>
       <tr>
        <td style="width: 353px">
           &nbsp;</td>
        </tr>               
  </table>
    
</asp:Content>
