<%@ Page Language="C#" MasterPageFile="~/Configure/ConfigureModule.Master" AutoEventWireup="true" CodeBehind="RecipeConfig.aspx.cs" Inherits="ezMESWeb.Configure.Process.RecipeConfig" Title="Untitled Page" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>
<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

<asp:ToolkitScriptManager ID="ToolkitScriptManager1" runat="server" />
<asp:Button ID="btnInsert" runat="server" Text="Insert" Width="147px" OnClick="btn_Click"/> 

<table style="width: 100%; height: 423px; margin-right: 0px; margin-top: 0px; border : 2px solid #6FBD06; ">
      <tr>
         <td style="height: 117px; width: 353px;">
   <asp:UpdatePanel ID="gvTablePanel" runat="server" UpdateMode="Conditional">
            <ContentTemplate>
         <asp:GridView ID="gvTable" runat="server" Caption="Recipe Configuration" 
               CssClass="datagrid" GridLines="None" DataSourceID="sdsRecipeGrid" 
               EmptyDataText="No recipe currently available" Height="145px" Width="500px"
               AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
               onselectedindexchanged="gvTable_SelectedIndexChanged" 
                DataKeyNames="id,name" AllowPaging="True"  AllowSorting="True" PageSize="15" 
               EnableTheming="False" onpageindexchanged="gvTable_PageIndexChanged"
             >
            <SelectedRowStyle  BackColor="#FFFFCC"/>
            <Columns>
             <asp:TemplateField><ItemTemplate>
			    <asp:LinkButton ID="btnViewDetails" runat="server" Text="Edit" CommandName="Select" />
			 </ItemTemplate></asp:TemplateField>
                <asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" SortExpression="id" />
                <asp:BoundField DataField="name" HeaderText="name" ReadOnly="True" SortExpression="name" />
                <asp:BoundField DataField="exec_method" HeaderText="exec_method" SortExpression="exec_method" />
                <asp:BoundField DataField="contact_employee" HeaderText="contact_employee" SortExpression="contact_employee" />
                <asp:BoundField DataField="create_time" HeaderText="create_time" SortExpression="create_time" />
                <asp:BoundField DataField="created_by" HeaderText="created_by" SortExpression="created_by" />
                <asp:BoundField DataField="update_time" HeaderText="update_time" SortExpression="update_time" />
                <asp:BoundField DataField="updated_by" HeaderText="updated_by" SortExpression="updated_by" />
                <asp:BoundField DataField="comment" HeaderText="comment" SortExpression="comment" />
                   	
			   </Columns>
                   </asp:GridView>
             </ContentTemplate>
              </asp:UpdatePanel> 
              
              
       <asp:SqlDataSource ID="sdsRecipeGrid" runat="server" 
           ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
           DeleteCommand="DELETE FROM step WHERE id=@id" 
           ProviderName="<%$ ConnectionStrings:ezmesConnectionString.ProviderName %>" 
           SelectCommand="select r.id, r.name, r.exec_method, r.contact_employee,
  r.create_time, r.created_by, r.update_time, r.updated_by, r.comment from recipe r, employee e
  where r.contact_employee = e.id and r.created_by = e.id "
InsertCommand="modify_recipe" InsertCommandType="StoredProcedure">
       </asp:SqlDataSource>
       
        <asp:Panel ID="RecordPanel" runat="server" ScrollBars="Auto" CssClass="detail" 
       style="margin-top: 19px;  height:500px; width:105%; display:none" HorizontalAlign="Left" >
   <asp:UpdatePanel ID="updateRecordPanel" runat="server" UpdateMode="Conditional">
   <ContentTemplate>
   <asp:Button id="btnShowPopup" runat="server" style="display:none" />
    <asp:ModalPopupExtender ID="ModalPopupExtender" runat="server" TargetControlID="btnShowPopup"
         BackgroundCssClass="modalBackground" PopupControlID="RecordPanel" 
        PopupDragHandleControlID="RecordPanel" Drag="True" DropShadow="True" >
        </asp:ModalPopupExtender>
        
       <asp:FormView ID="FormView1" runat="server" DataSourceID="sdsRecipeConfig"
       EnableTheming="True" Height="100px" HorizontalAlign="Center" Width="100%" CssClass="detailgrid" DefaultMode="Insert" CellPadding="4" ForeColor="#333333" 
       >      
       </asp:FormView>
          <asp:SqlDataSource ID="sdsRecipeConfig" runat="server" 
       ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>"
       ProviderName="<%$ ConnectionStrings:ezmesConnectionString.ProviderName %>"  InsertCommand="Insert"
       SelectCommand="select r.id, r.name, r.exec_method, r.contact_employee,
  r.create_time, r.created_by, r.update_time, r.updated_by, r.comment from recipe r, employee e
  where r.contact_employee = e.id and r.created_by = e.id and r.id = @vid" 
        >
       <SelectParameters>
           <asp:ControlParameter ControlID="gvTable" Name="vid" 
            PropertyName="SelectedValue" />
       </SelectParameters>
       
       </asp:SqlDataSource>
       
         <div class="footer">
          <asp:LinkButton ID="btnSubmit" runat="server" CausesValidation="True" 
            OnClick="btnSubmit_Click"  Text="Submit" />&nbsp;
          <asp:LinkButton ID="btnCancel" runat="server" 
           CausesValidation="False" CommandName="Cancel" OnClick="btnCancel_Click"
             Text="Cancel" />
       </div>
       <asp:Label ID="lblError" runat="server" ForeColor="#FF3300" 
                Height="60px" Width="350px"></asp:Label>
                               
      </ContentTemplate>
      </asp:UpdatePanel>
       </asp:Panel>  
 
      </td>
       </tr>
       <tr>
        <td style="width: 353px">
           &nbsp;</td>
        </tr>               
  </table>


</asp:Content>
