<%@ Page Language="C#" MasterPageFile="../ConfigureModule.master" AutoEventWireup="true" CodeBehind="OrderConfig_old.aspx.cs" Inherits="ezMESWeb.Configure.OrderConfig" Title="Order Config Page" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>

<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">

</asp:Content>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
     
<asp:ToolkitScriptManager ID="ToolkitScriptManager1" runat="server" />

<asp:Button ID="btnInsert" runat="server" Text="Insert" Width="147px" OnClick="btn_Click"/> 
               
<table style="width: 100%; height: 423px; margin-right: 0px; margin-top: 0px; border : 2px solid #6FBD06; ">
      <tr>
         <td style="height: 117px; width: 353px;">
   <asp:UpdatePanel ID="gvTablePanel" runat="server" UpdateMode="Conditional">
            <ContentTemplate>
             <asp:GridView ID="gvTable" runat="server" Caption="Simple LED's Customer Orders" 
               CssClass="datagrid" GridLines="None" DataSourceID="sdsPDGrid" 
               EmptyDataText="No Order currently available" Height="145px" Width="500px"
               AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
               onselectedindexchanged="gvTable_SelectedIndexChanged" 
                DataKeyNames="id" AllowPaging="True"  AllowSorting="True" PageSize="15" 
               EnableTheming="False" onpageindexchanged="gvTable_PageIndexChanged"
             >
             <Columns>
             <asp:TemplateField>
			   <ItemTemplate>
			       <asp:LinkButton ID="btnViewDetails" runat="server" Text="Edit" CommandName="Select" />
			     </ItemTemplate>                 
                 </asp:TemplateField>
                 <asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" SortExpression="id" />
                 <asp:BoundField DataField="order_type" HeaderText="Order Type" SortExpression="order_type" />
                 <asp:BoundField DataField="ponumber" HeaderText="PO Num" SortExpression="ponumber" />
                 <asp:BoundField DataField="ClientName" HeaderText="Client" SortExpression="ClientName" />
                 <asp:BoundField DataField="PriName" HeaderText="Priority" SortExpression="PriName" />
                 <asp:BoundField DataField="ProductName" HeaderText="Product" SortExpression="ProductName" />
                 <asp:BoundField DataField="quantity_requested" HeaderText="Qty Requested" SortExpression="quantity_requested" />
                 <asp:BoundField DataField="quantity_made" HeaderText="Qty Made" SortExpression="quantity_made" />
                 <asp:BoundField DataField="quantity_in_process" HeaderText="Qty In Process"
                     SortExpression="quantity_in_process" />
                 <asp:BoundField DataField="quantity_shipped" HeaderText="Qty Shipped" SortExpression="quantity_shipped" />
                 <asp:BoundField DataField="uom" HeaderText="Unit" SortExpression="uom" />
                 <asp:BoundField DataField="order_date" HeaderText="Order Date" SortExpression="order_date" />
                 <asp:BoundField DataField="output_date" HeaderText="Output Date" SortExpression="output_date" />
                 <asp:BoundField DataField="expected_deliver_date" HeaderText="Expected Deliver Date"
                     SortExpression="expected_deliver_date" />
                 <asp:BoundField DataField="actual_deliver_date" HeaderText="Actual Deliver Date"
                     SortExpression="actual_deliver_date" />
                 <asp:BoundField DataField="internal_contact_name" HeaderText="Internal Contact" SortExpression="internal_contact_name" />
                 <asp:BoundField DataField="external_contact" HeaderText="External Contact" SortExpression="external_contact" />
                 <asp:BoundField DataField="comment" HeaderText="Comment" SortExpression="comment" />
                   	
			   </Columns>
               <SelectedRowStyle  BackColor="#FFFFCC"/>
                </asp:GridView>
               </ContentTemplate>
              </asp:UpdatePanel> 
              
       <asp:SqlDataSource ID="sdsPDGrid" runat="server" 
           ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
           DeleteCommand="DELETE FROM `order` WHERE `order`.id=@id" 
           ProviderName="<%$ ConnectionStrings:ezmesConnectionString.ProviderName %>" 
       SelectCommand="
       SELECT `order`.id, 
  `order`.order_type, 
  `order`.ponumber, 
  `order`.client_id,
   client.name as ClientName,
   `order`.priority,
   priority.Name as PriName,
   `order`.product_id, 
   product.name as ProductName,
  `order`.quantity_requested, 
  `order`.quantity_made, 
  `order`.quantity_in_process, 
  `order`.quantity_shipped, 
  `order`.uomid,
  uom.Name as uom,
  `order`.order_date, 
  `order`.output_date, 
  `order`.expected_deliver_date, 
  `order`.actual_deliver_date, 
  `order`.internal_contact,
  employee.firstname ||' '||employee.lastname as internal_contact_name,
  `order`.external_contact, 
  `order`.comment 
  FROM `order` INNER JOIN product ON `order`.product_id = product.id 
       LEFT JOIN client ON `order`.client_id = client.id 
       INNER JOIN priority ON `order`.priority = priority.ID 
       INNER JOIN uom ON `order`.uomid = uom.id 
       INNER JOIN employee ON `order`.internal_contact = employee.id
       " 
       InsertCommand="insert_order" InsertCommandType="StoredProcedure"
        EnableCaching="false">
        </asp:SqlDataSource>
  
  <asp:Panel ID="RecordPanel" runat="server" ScrollBars="Auto" CssClass="detail" 
       style="margin-top: 19px;  height:500px; width:105%; display:none" HorizontalAlign="Left" >
   <asp:UpdatePanel ID="updateRecordPanel" runat="server" UpdateMode="Conditional">
   <ContentTemplate>
   <asp:Button id="btnShowPopup" runat="server" style="display:none" />
    <asp:ModalPopupExtender ID="ModalPopupExtender" runat="server" TargetControlID="btnShowPopup"
         BackgroundCssClass="modalBackground" PopupControlID="RecordPanel" 
        PopupDragHandleControlID="RecordPanel" Drag="True" DropShadow="True" >
        </asp:ModalPopupExtender>
        
       <asp:FormView ID="FormView1" runat="server" DataSourceID="sdsOrder"
       EnableTheming="True" Height="100px" 
       HorizontalAlign="Center" Width="100%" CssClass="detailgrid" DefaultMode="Insert" CellPadding="4" ForeColor="#333333" 
       >      
       </asp:FormView>
       
       <asp:SqlDataSource ID="sdsOrder" runat="server" 
       ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
       ProviderName="<%$ ConnectionStrings:ezmesConnectionString.ProviderName %>"  InsertCommand="Insert"
       EnableCaching="false"
       SelectCommand="SELECT `order`.order_type, `order`.ponumber, `order`.client_id, 
       `order`.priority, `order`.product_id, `order`.quantity_requested, `order`.quantity_made, `order`.quantity_in_process, `order`.quantity_shipped, `order`.uomid, `order`.order_date, `order`.output_date, `order`.expected_deliver_date, `order`.actual_deliver_date, `order`.internal_contact, `order`.external_contact, `order`.comment 
       FROM `order`, product, client, priority, uom, employee
       WHERE `order`.product_id = product.id and 
             `order`.client_id = client.id and
             `order`.priority = priority.ID and
             `order`.uomid = uom.id and
             `order`.internal_contact = employee.id and
             `order`.id = @vid" 
             
        >
         <SelectParameters>
           <asp:ControlParameter ControlID="gvTable" Name="vid" 
            PropertyName="SelectedValue" />
       </SelectParameters>
       </asp:SqlDataSource>
       
       <div class="footer">
          <asp:LinkButton ID="btnSubmit" runat="server" CausesValidation="True" 
            OnClick="btnSubmit_Click"  Text="Submit" />&nbsp;
          <asp:LinkButton ID="btnCancel" runat="server" 
           CausesValidation="False" CommandName="Cancel" OnClick="btnCancel_Click"
             Text="Cancel" />
       </div>
       <asp:Label ID="lblError" runat="server" ForeColor="#FF3300" 
                Height="60px" Width="350px"></asp:Label>
                  
      </ContentTemplate>
      </asp:UpdatePanel>
       </asp:Panel>  
 
      </td>
       </tr>
       <tr>
        <td style="width: 353px">
           &nbsp;</td>
        </tr>               
  </table>
  
  
</asp:Content>

