<%@ Page Language="C#" MasterPageFile="~/Configure/ConfigureModule.Master" AutoEventWireup="true" CodeBehind="EquipmentConfig.aspx.cs" Inherits="ezMESWeb.Configure.Equipment.EquipmentConfig" Title="Equipment Configuration -- ezOOM" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>

<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
<asp:ToolkitScriptManager ID="ToolkitScriptManager1" runat="server" />
<asp:Button ID="btnInsert" runat="server" Text="Insert" Width="147px" OnClick="btn_Click"/> 
<asp:panel id="pnlScroll" runat="server" width="78%" 
height="100%" scrollbars="Horizontal">          
   <asp:UpdatePanel ID="gvTablePanel" runat="server" UpdateMode="Conditional">
            <ContentTemplate>
             <asp:GridView ID="gvTable" runat="server" Caption="Equipment" 
               CssClass="datagrid" GridLines="None" DataSourceID="sdsEQGrid" 
               EmptyDataText="No equipment currently available" Height="145px" Width="500px"
               AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
               onselectedindexchanged="gvTable_SelectedIndexChanged"  
               DataKeyNames="id" AllowPaging="True"  AllowSorting="True" PageSize="15" EnableTheming="False" 
               onpageindexchanged="gvTable_PageIndexChanged"
             >
             <Columns>
               <asp:TemplateField>
               <ItemTemplate>
			       <asp:LinkButton ID="btnViewDetails" runat="server" Text="Edit" CommandName="Select" />
			     </ItemTemplate>
				 </asp:TemplateField>	
              
                 <asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" SortExpression="id" />
                 <asp:BoundField DataField="name" HeaderText="Name" SortExpression="name" />
                  <asp:BoundField DataField="state" HeaderText="State" SortExpression="state" />
                   <asp:BoundField DataField="create_time" HeaderText="Create Time" SortExpression="create_time" />
                   <asp:BoundField DataField="creater" HeaderText="Created By" SortExpression="creater" />
                   <asp:BoundField DataField="state_change_time" HeaderText="State Change Time" SortExpression="state_change_time" />
                 <asp:BoundField DataField="state_changer" HeaderText="State Changed By" SortExpression="state_changer" />
                 <asp:BoundField DataField="contact_person" HeaderText="Contact Person" SortExpression="contact_person" />
                 <asp:BoundField DataField="manufacture_date" HeaderText="Manufacture Date" SortExpression="manufacture_date" />
                 <asp:BoundField DataField="manufacturer" HeaderText="Manufacturer" SortExpression="manufacturer" />
                 <asp:BoundField DataField="manufacturer_phone" HeaderText="Manufacturer Phone" SortExpression="manufacturer_phone" />
                 <asp:BoundField DataField="online_date" HeaderText="Online Date" SortExpression="online_date" />
                 <asp:BoundField DataField="description" HeaderText="description" SortExpression="description" />
                 <asp:BoundField DataField="comment" HeaderText="comment" SortExpression="comment" />
                   	
			   </Columns>
               <SelectedRowStyle  BackColor="#FFFFCC"/>
                </asp:GridView>
               </ContentTemplate>
              </asp:UpdatePanel> 
           </asp:panel>
              
       <asp:SqlDataSource ID="sdsEQGrid" runat="server" 
           ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
           DeleteCommand="{call delete_equipment(?,?) }" 
           ProviderName="System.Data.Odbc" 
       SelectCommand="SELECT eq.id, 
                           eq.name, 
                          eq.state, 
                    eq.create_time, 
                     eq.created_by, 
                     concat(e1.firstname, ' ', e1.lastname) as creater,
                  eq.state_change_time,
                  eq.state_changed_by,
                  concat(e2.firstname, ' ', e2.lastname) as state_changer,
                  eq.contact_employee,
                  concat(e3.firstname, ' ', e3.lastname) as contact_person,
                  eq.manufacture_date,
                  eq.manufacturer, 
                  eq.manufacturer_phone,
                  eq.online_date,
                  eq.description,
                  eq.comment
                  FROM Equipment eq
                  LEFT JOIN employee e1 ON e1.id = eq.created_by
                  LEFT JOIN employee e2 ON e2.id = eq.state_changed_by
                  LEFT JOIN employee e3 ON e3.id = eq.contact_employee" DeleteCommandType="StoredProcedure">
           <DeleteParameters>
               <asp:SessionParameter Name="Eid" SessionField="UserID" />
           </DeleteParameters>
        </asp:SqlDataSource>
        
         <asp:Panel ID="RecordPanel" runat="server" ScrollBars="Auto" CssClass="detail" 
       style="margin-top: 19px;  height:500px; width:370px; display:none" HorizontalAlign="Left" >
   <asp:UpdatePanel ID="updateRecordPanel" runat="server" UpdateMode="Conditional">
   <ContentTemplate>
   <asp:Button id="btnShowPopup" runat="server" style="display:none" />
    <asp:ModalPopupExtender ID="ModalPopupExtender" runat="server" TargetControlID="btnShowPopup"
         BackgroundCssClass="modalBackground" PopupControlID="RecordPanel" 
        PopupDragHandleControlID="RecordPanel" Drag="True" DropShadow="True" >
        </asp:ModalPopupExtender>
        
         <asp:FormView ID="FormView1" runat="server" DataSourceID="sdsEQConfig"
       EnableTheming="True" Height="100px" HorizontalAlign="Center" Width="100%" CssClass="detailgrid" DefaultMode="Insert" CellPadding="4" ForeColor="#333333" 
       >      
       </asp:FormView>
          <asp:SqlDataSource ID="sdsEQConfig" runat="server" 
       ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
       EnableCaching="false"
       ProviderName="System.Data.Odbc" 
       SelectCommand="SELECT name, state, contact_employee, manufacture_date, manufacturer, manufacturer_phone, online_date, description, comment
           FROM equipment WHERE id = ?" 
        >
        <SelectParameters>
           <asp:ControlParameter ControlID="gvTable" Name="vid" 
            PropertyName="SelectedValue" />
       </SelectParameters>
       
       </asp:SqlDataSource>
       
         <div class="footer">
          <asp:LinkButton ID="btnSubmit" runat="server" CausesValidation="True" 
            OnClick="btnSubmit_Click"  Text="Submit" />&nbsp;
          <asp:LinkButton ID="btnCancel" runat="server" 
           CausesValidation="False" CommandName="Cancel" OnClick="btnCancel_Click"
             Text="Cancel" />
       </div>
       <asp:Label ID="lblError" runat="server" ForeColor="#FF3300" 
                Height="60px" Width="350px"></asp:Label>
                               
      </ContentTemplate>
      </asp:UpdatePanel>
       </asp:Panel>  
    
</asp:Content>
