<%@ Page Language="C#" MasterPageFile="~/Configure/ConfigureModule.Master" AutoEventWireup="true" CodeBehind="IngredientsConfig.aspx.cs" Inherits="ezMESWeb.Configure.Material.IngredientsConfig" Title="Untitled Page" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>
<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
<asp:ToolkitScriptManager ID="ToolkitScriptManager1" runat="server" />
<table style="width: 100%; height: 423px; margin-right: 0px; margin-top: 0px; border : 2px solid #6FBD06; ">
      <tr>
         <td style="height: 117px; width: 353px;">
   <asp:UpdatePanel ID="gvTablePanel" runat="server" UpdateMode="Conditional">
            <ContentTemplate>
             <asp:GridView ID="gvTable" runat="server" Caption="Ingredient" 
               CssClass="datagrid" GridLines="None" DataSourceID="sdsIngredientGrid" 
               EmptyDataText="No ingredient currently available" Height="145px" Width="500px"
               AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
               onselectedindexchanged="gvTable_SelectedIndexChanged"  
               DataKeyNames="recipe_id,source_type,ingredient_id" AllowPaging="True"  AllowSorting="True" PageSize="15" EnableTheming="False" 
               onpageindexchanged="gvTable_PageIndexChanged"
             >
             <Columns>
                 <asp:BoundField DataField="recipe_id" HeaderText="recipe_id" ReadOnly="True" SortExpression="recipe_id" />
                 <asp:BoundField DataField="source_type" HeaderText="source_type" ReadOnly="True"
                     SortExpression="source_type" />
                 <asp:BoundField DataField="ingredient_id" HeaderText="ingredient_id" ReadOnly="True"
                     SortExpression="ingredient_id" />
                 <asp:BoundField DataField="quantity" HeaderText="quantity" SortExpression="quantity" />
                 <asp:BoundField DataField="uom_id" HeaderText="uom_id" SortExpression="uom_id" />
                 <asp:BoundField DataField="order" HeaderText="order" SortExpression="order" />
                 <asp:BoundField DataField="mintime" HeaderText="mintime" SortExpression="mintime" />
                 <asp:BoundField DataField="maxtime" HeaderText="maxtime" SortExpression="maxtime" />
                 <asp:BoundField DataField="comment" HeaderText="comment" SortExpression="comment" />
                   	
			   </Columns>
               <SelectedRowStyle  BackColor="#FFFFCC"/>
                </asp:GridView>
               </ContentTemplate>
              </asp:UpdatePanel> 
              
       <asp:SqlDataSource ID="sdsIngredientGrid" runat="server" 
           ConnectionString="<%$ ConnectionStrings:ezmesConnectionString %>" 
           DeleteCommand="DELETE FROM ingredients WHERE id=@id" 
           ProviderName="<%$ ConnectionStrings:ezmesConnectionString.ProviderName %>" 
       SelectCommand="SELECT * FROM ingredients" >
        </asp:SqlDataSource>
       <!-- Add insert/edit form later-->
        
        </td>
       </tr>
       <tr>
        <td style="width: 353px">
           &nbsp;</td>
        </tr>               
  </table>
</asp:Content>
